- aphrodite/__init__.py
- aphrodite/engine/aphrodite_engine.py
- aphrodite/modeling/models/__init__.py
- aphrodite/modeling/models/gpt_j.py
- aphrodite/transformers_utils/tokenizer.py
- requirements.txt
Mostly same as upstream:
- Removed code related to training
- Inputs and positions flattened to 1D
- Attention replaced with [`PagedAttentionWithRoPE`](https://github.com/PygmalionAI/aphrodite-engine/blob/fd35ba84b0f6c4a22b6370773393fc2a773959e0/aphrodite/modeling/layers/attention.py#L162)
- Tensor Parallelism (in case we use smaller GPUs to load the model)
> feat: support for GPT-J HF

- aphrodite/common/logits.py
No current LogitProcessor uses that argument, but this unbreaks the feature.
> Fix LogitProcessor infrastructure

- LICENSE
[As discussed](https://github.com/PygmalionAI/aphrodite-engine/discussions/37), the change from AGPL to MIT may have been a mistake. This would not allow us to use code from other AGPL-licensed repositories such as KoboldAI. As such, we plan to move back to a pure AGPL license. Apologies for the mess this has caused. 
All contributors are assigned as reviewers, and we will merge once everyone approves this PR.
Tagging @50h100a and @g4rg as well.
> Revert license back to AGPLv3

- aphrodite/endpoints/api_server_kobold.py
- aphrodite/endpoints/protocol.py
KAI API allows `tfs = 0`, but aphrodite doesn't
KAI API allows `temp = 0` (although perhaps it shouldn't), aphrodite implies greedy sampling in that case.
I think ideally, this should instead fail or produce a warning, but horde puts the worker into maintenance if it does.
> fix: more KAI parameter adaptations

- aphrodite/modeling/quantization_utils/awq.py
- kernels/quantization/awq/dequantize.cuh
- kernels/quantization/awq/gemm_kernels.cu
This PR adds a condition to build AWQ kernels for Turing GPUs, by dividing the two `m16n8k16` sync operations into 4 `m16n8k8` operations instead. This might lead to slight slow-downs, but nothing too drastic. It should compile as normal for Ampere and higher GPUs.
> feat: AWQ support for Turing GPUs

- update-runtime.sh
Added `export CUDA_HOME=$(find / -type d -path "*/conda/envs/linux" 2>/dev/null | head -n 1)` to find envs with the name `linux` which is what @henk717 defined.
> Make NVCC work for different versions

- update-runtime.sh
This PR allows the user to specify whether to build the engine from source or grab a prebuilt wheel off pypi.
> chore: allow the user to specify install method

- requirements.txt
By locking Ray to version 2.5.1 the bug--->https://github.com/ray-project/ray/issues/39803 will not occur
> Locked Ray version to 2.5.1

- aphrodite/endpoints/api_server_kobold.py
It appears calling `await raw_request.is_disconnected()` on every token regularly causes multiple non-streaming requests to get stuck, then flushed out all at the same time. It becomes evident when connecting a horde worker.
Not sure what the root cause is. A computationally expensive coroutine delaying async tasks, perhaps?
The same pattern is used in the other endpoints' non-streaming case.
> fix: requests stalling in KAI non-streaming endpoint

- aphrodite/modeling/layers/sampler.py
- aphrodite/modeling/metadata.py
- aphrodite/task_handler/worker.py
Should fix the overhead introduced in #66 by indexing sampler type and pre-allocating  tensors used to prune hidden states.
> fix: prompt processing overhead introduced by #66

- kernels/quantization/awq/gemm_kernels.cu
Instead of the default Stream, we should make sure the kernels launch on the *current* CUDAStream.
> fix: launch AWQ kernels on the current CUDAStream

- aphrodite/common/config.py
The correct NTK alpha (at least for llama2) isn't actually that linear. For example if you want 8192 context size, the most optimal value is around 2.6, not 2.
> fix: correct auto ntk scaling_factor for 4k ctx case

- docker/docker-compose.yml
- docker/entrypoint.sh
`docker-compose.yml` and `entrypoint.sh` have different ports configured. 
I reverted `entrypoint.sh` port back to 2242, seems that seems to be default port used in other documentation and `docker-compose.yml` as well.
> Fix docker port

- aphrodite/endpoints/openai/api_server.py
We currently expect the API keys through an `x-api-key: API_KEY` header. For maximum compatibility, this PR introduces support for `Authorization: Bearer API_KEY` alongside the current implementation.
> add authorization bearer support for OAI endpoint

- aphrodite/modeling/layers/attention.py
- aphrodite/modeling/layers/rotary_embedding.py
The current RoPE scaling implementation is inside the attention code. This PR is an attempt at debloating it by moving the RoPE scaling detection to the `rotary_embedding.py` module.
Needs testing before merge.
> chore: rope refactors

- aphrodite/common/config.py
Save a call cycle when validating torch.dtype.
> feat: parse torch.dtype properly

- aphrodite/engine/aphrodite_engine.py
The ignored seq group in engine step is duplicated, which would lead to incorrect number of outputs in batch generations with long prompts.
> fix: duplication in engine

- aphrodite/common/config.py
- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/args_tools.py
- aphrodite/task_handler/worker.py
This PR adds the `--max-parallel-loading-workers` flag for allocating workers when loading models. Should be helpful for large models in parallelism.
> fix: CPU OOM with large models using parallelism

- aphrodite/modeling/loader.py
We initialize the model entirely on the GPU to avoid unnecessary CPU usage.
> chore: initialize model on GPU

- aphrodite/endpoints/openai/api_server.py
[chatbot-ui](https://github.com/mckaywrigley/chatbot-ui) uses chat completions endpoint, and it sets SeparatorStyle to None, but there's no `None` in FastChat's separator styles. This PR sets it to `LLAMA2` if it's None.
> fix: OAI chat completions Separator Style

- aphrodite/endpoints/openai/api_server.py
- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/metrics.py
- requirements.txt
This PR adds Prometheus metrics at the OpenAI server's `/metrics` endpoint. Light dependency so it should be fine.
> feat: add prometheus production metrics

- aphrodite/modeling/layers/activation.py
- aphrodite/modeling/layers/layernorm.py
- aphrodite/modeling/layers/rotary_embedding.py
This PR implements pure PyTorch versions of the activation functions, layernorm, and the two rotary embedding styles. Mainly for testing purposes.
> chore: implement torch native layers

- aphrodite/modeling/loader.py
- aphrodite/modeling/models/__init__.py
- aphrodite/modeling/models/decilm.py
The PR adds the newly released [Deci-LM](https://huggingface.co/Deci/DeciLM-7B) models. 
The model architecture is pretty much the same as Llama, with the addition of Variable GQA. More details in the class docstrings.
> feat: implement Deci-LM

- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/async_aphrodite.py
NCCL needs mutiple separate devices to work properly. But Ray doesn't know this and tries to squeeze the placement group into as few GPUs as it can. If Ray ends up choosing fewer GPUs than the tensor parallelism factor, NCCL won't work. The only workaround right now is to avoid using fractional GPUs when the tensor parallelism factor is more than 1.
> fix: tensor parallelism at more than 1 GPU

- aphrodite/modeling/models/llama.py
ColossalAI seems to also save the sin and cos rotary embedding cache into the model after training. We can't handle those so we skip them.
> fix: KeyError in Llama models

- aphrodite/endpoints/openai/api_server.py
Fix for error `local variable completion_tokens referenced before assignment.`
> fix: OpenAI chat - reference before assignment

- aphrodite/endpoints/openai/api_server.py
This PR fixes `echo` and `prompt_logprobs` for the OpenAI server.
To request prompt logprobs, run:
```sh
curl http://localhost:2242/v1/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer sk-example-key" \
-d '{
"model": "PygmalionAI/pygmalion-2-7b",
"prompt": "Every age it seems is tainted by the greed of men. Rubbish to one such as I,",
"stream": false,
"min_p: 0.05,
"echo": true,
"logprobs": 1,
"prompt_logprobs": 1
}'
```
You need to request regular logprobs (for the output) if you want to request prompt logprobs.
> fix: echo and prompt logprobs

- aphrodite/task_handler/model_runner.py
Mistral and Mixtral models specify the sliding window as 4096 by default and that remains unchanged, resulting in extremely poor results at over 4k prompt length. This fixes that.
> fix: sliding window for mistral/mixtral

- aphrodite/common/utils.py
- aphrodite/task_handler/worker.py
Fix the memory peak profiling to significantly improve the KV cache allocation.
Dev branch:
1x NVIDIA A40, Mistral 7B BF16
`# GPU blocks: 13228, # CPU blocks: 2048`
This PR:
1x NVIDIA A40, Mistral 7B BF16
`# GPU blocks: 10535, # CPU blocks: 2048`
This should make much higher gpu_memory_utilization (gmu) values possible.
> fix: memory profiling

- aphrodite/modeling/layers/linear.py
- aphrodite/modeling/layers/quantization/gptq.py
- aphrodite/modeling/layers/quantization/squeezellm.py
- kernels/ops.h
This PR re-writes the exllama states and removes the warning for the missing fused linear layers, such as the `output_dim` in QKVParallelLinear.
> fix: GPTQ warnings and exllama states

- aphrodite/modeling/models/mixtral.py
This adds `rope_scaling` to the mixtral decoder.
Useful for llama2 MoE's with 4k native context.
> Mixtral RoPE scaling (2)

- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/ray_tools.py
Hopefully closes #115.
We now use psutil. This method also now is more cross-platform thanks to it. There is an improvement when the requests are split across multiple cores.
The reason why it is labeled as a hack is that we are applying the said affinities *after*the workers have been initialized.
I have found that trying to set it to before (RayWorkers generated from the bundles in the code above don't get affinities applied) or clearing (Clearing affinities set them back to (0,1) in my testing) doesn't yield good results. By explicitly setting affinities, we can avoid those problems.
I've also added a hyper-threading check. Not too sure what other method I can use from psutil but eh, it works?
> Set CPU Affinity: Electric Boogaloo V2

- aphrodite/common/config.py
- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/args_tools.py
- aphrodite/modeling/layers/attention.py
- aphrodite/task_handler/cache_engine.py
- aphrodite/task_handler/worker.py
- kernels/attention/attention_dtypes.h
- kernels/attention/attention_kernels.cu
- kernels/attention/dtype_fp8.cuh
- kernels/cache.h
- kernels/cache_kernels.cu
- kernels/dispatch_utils.h
- kernels/ops.h
- kernels/pybind.cpp
- kernels/quantization/kvcache/quant_utils.cuh
This PR adds the option to use FP8 datatype for the KV cache. Accuracy loss should be minimal (less than 1%), and it should lead to speedups for H100s and some memory savings for older GPUs.
> feat: FP8 KV Cache (ENG-4)

- aphrodite/endpoints/openai/api_server.py
Requires the API key to query. Example curl request:
```sh
curl -X 'POST' \
'http://localhost:2242/v1/tokenize' \
-H 'accept: application/json' \
-H 'x-api-key: EMPTY' \
-H 'Content-Type: application/json' \
-d '{
"prompt": "The quick brown fox jumped over the lazy fox"
}'
```
Response:
```json
{
"value": 11,
"ids": [
415,
2936,
9060,
285,
1142,
14949,
754,
272,
17898,
285,
1142
]
}
```
> feat: tokenizer endpoint for OpenAI API

- aphrodite/modeling/layers/moe.py
For some reason, triton doesn't work with simultaneous multiple comparisons.
> fix: triton compile error

- aphrodite/modeling/models/mixtral.py
The current Tensor Parallel implementation struggles with quantized models. Until I can figure out a fix for that, we'll fallback to the old expert parallel implementation if a quantized model is loaded. very hacky, must fix soon.
> fix: use tensor parallel for quantized mixtral

- aphrodite/endpoints/openai/api_server.py
As described in #183, the logprobs JSON construction fails if a value is NaN, could be -inf for example. Fix is the same as provided by @miku448 in the issue.
> fix: logprobs at -inf

- aphrodite/modeling/layers/quantization/awq.py
- kernels/ops.h
- kernels/pybind.cpp
- kernels/quantization/awq/gemm_kernels.cu
This PR speeds up AWQ quantized models by a fair bit.
Mistral 7B AWQ, NVIDIA A40:
**Before**
Throughput: 3.89 requests/s, Input tokens/s: 981.59, Output tokens/s: 870.20
**After**
Throughput: 4.92 requests/s, Input tokens/s: 1242.21, Output tokens/s: 1101.24
> feat: speedup AWQ

- aphrodite/endpoints/kobold/api_server.py
Similar to the OpenAI server, will spawn a prometheus metrics page at `/metrics` route.
> feat: add `/metrics` route for kobold

- aphrodite/modeling/layers/sampler.py
It crashes with `RuntimeError: The size of tensor a (2) must match the size of tensor b (32000) at non-singleton dimension 1` without it.
I never used pytorch in my life, though.
> Fix crash in quadratic sampling when batch size > 1

- aphrodite/common/grammar.py
- aphrodite/endpoints/openai/api_server.py
This pull request addresses:
1. The function signature of `GrammarLogitsProcessor` does not match with the current implementation of `_apply_logits_processors` in `sampler.py`
2. The use of Ray to filter logits results in a significant slowdown on my local machine. Given performance is the priority, and I haven't seen any drawbacks to doing so, I have removed the grammar module's dependency on Ray.
> Fix grammar logits processor

- aphrodite/task_handler/worker.py
This patch is to fix https://github.com/microsoft/WSL/issues/10269 Unexpected error occurring when attempting to initialise a worker on WSL.
> Patch for WSL unexpected error

- aphrodite/engine/async_aphrodite.py
Explicitly use the remote method for `encode_request_async` if engine is launched with Ray.
> fix: remote encode request if using ray

- kernels/attention/attention_kernels.cu
- kernels/cache_kernels.cu
- kernels/quantization/fp8_e5m2_kvcache/quant_utils.cuh
ROCm doesn't support FP8 intrinsic yet, let's not build it.
> fix: FP8 KV Cache errors on ROCm

- aphrodite/engine/aphrodite_engine.py
Due to (somewhat) popular demand, we should probably remove the EOS token from the output by default.
> chore: remove eos token from output

- aphrodite/endpoints/openai/api_server.py
Note to self: don't try to recognize args that way, it doesn't work as well.
> fix: arg detection for kobold api launch

- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/async_aphrodite.py
- tests/async_engine/test_async_aphrodite.py
- tests/async_engine/test_request_tracker.py
Some errors may silently fail and not inform the user. This would be useful in production scenarios.
> chore: add health check for ray workers

- aphrodite/common/config.py
- aphrodite/engine/args_tools.py
- aphrodite/modeling/layers/linear.py
- aphrodite/modeling/layers/quantization/__init__.py
- aphrodite/modeling/layers/quantization/aqlm.py
- aphrodite/modeling/layers/quantization/awq.py
- aphrodite/modeling/layers/quantization/gguf.py
- aphrodite/modeling/layers/quantization/gptq.py
- aphrodite/modeling/layers/quantization/marlin.py
- aphrodite/modeling/layers/quantization/quip.py
- aphrodite/modeling/layers/quantization/squeezellm.py
- aphrodite/modeling/layers/vocab_parallel_embedding.py
- kernels/ops.h
- kernels/pybind.cpp
- kernels/quantization/aqlm/LICENSE
- kernels/quantization/aqlm/aqlm_cuda_entry.cpp
- kernels/quantization/aqlm/aqlm_cuda_kernel.cu
- setup.py
Huge thanks to Neural Magic and their work on making this possible.
Reference:
https://github.com/Vahe1994/AQLM
https://arxiv.org/pdf/2401.06118.pdf
AQLM is a SOTA 2-bit and 3-bit quantization algorithm, superior to QuIP# in perplexity measurements. At the moment, the kernels aren't too optimized, and as a result, the prompt processing time is horrendously slow. Needs `--enforce-eager` to launch. Because of the slow dequantization, loading models takes a long time.
Some models to test:
https://huggingface.co/collections/ISTA-DASLab/aqlm-65e8dc75b908c7d73ec35598
> feat: AQLM quantization support

- aphrodite/common/config.py
- aphrodite/engine/args_tools.py
- aphrodite/modeling/layers/quantization/__init__.py
- aphrodite/modeling/layers/quantization/bitsandbytes.py
- aphrodite/modeling/loader.py
- kernels/ops.h
- kernels/pybind.cpp
- kernels/quantization/bitsandbytes/common.h
- kernels/quantization/bitsandbytes/cta_iterator.h
- kernels/quantization/bitsandbytes/format.cu
- kernels/quantization/bitsandbytes/format.h
- kernels/quantization/bitsandbytes/gemm_s4_f16.cu
- kernels/quantization/bitsandbytes/gemm_s4_f16.h
- kernels/quantization/bitsandbytes/gemm_s4_f16_kernel.h
- kernels/quantization/bitsandbytes/gemm_template.h
- kernels/quantization/bitsandbytes/int4_fp16_gemm_kernels.cu
- kernels/quantization/bitsandbytes/metric.h
- kernels/quantization/bitsandbytes/warp_iterator.h
- requirements.txt
- setup.py
- tests/benchmarks/throughput.py
This PR adds support for 3 new quant methods, based off Smoothquant and Bitsandbytes. Use `--load-in-4bit` to convert the FP16 model weights to 4bit at runtime, leading to a roughly 150% throughput increase. e.g. Mistral 7B on an A40 achieves up to 80 T/s, compared to 32 on pure FP16.
`--load-in-4bit` works with FP16 and AWQ models.
`--load-in-8bit` and `--load-in-smooth` work with FP16 models only.
> feat: bitsandbytes and `--load-in{4,8}bit` support

- aphrodite/common/logger.py
Thanks to @bdashore3 for finding out about `escape` from `rich.markup`.
Still have to manually escape `<` since that doesn't do anything if they appear to be part of a tag, e.g. `<START>`.
> fix: escape tags in loguru

- aphrodite/__init__.py
Finally. Need to take care of an issue before release.
FIX:
> chore: bump version to 0.5.0

- aphrodite/endpoints/openai/api_server.py
- aphrodite/endpoints/openai/serving_engine.py
Examples:
Loading a LoRA:
```sh
curl -X 'POST' \
'http://localhost:2242/v1/lora/load' \
-H 'accept: application/json' \
-H 'x-api-key: testing-admin' \
-H 'Content-Type: application/json' \
-d '{
"name": "storywriter",
"local_path": "/home/anon/models/lora/13b-storywriter"
}'
```
Unloading a LoRA:
```sh
curl -X 'DELETE' \
'http://localhost:2242/v1/lora/unload?lora_name=storywriter' \
-H 'accept: application/json' \
-H 'x-api-key: testing-admin'
```
Keep in mind that loading/unload needs an admin API key, added with `--admin-key`.
> feat: enable lora loading/unloading via API

- docker/.env
- requirements.txt
@AlpinDale As discussed in [Pull Request #338](https://github.com/PygmalionAI/aphrodite-engine/pull/338), I've added hf_transfer for faster downloads.
The official docs ([Environment variables](https://huggingface.co/docs/huggingface_hub/v0.21.4/package_reference/environment_variables#hfhubenablehftransfer)) list its limitations and state "Consequently, `hf_transfer` is not enabled by default in `huggingface_hub`." That's why I've added it to the envfile, but kept it commented out, so users can actively but easily choose to enable it.
Also changed HUGGING_FACE_HUB_TOKEN to HF_TOKEN in the envfile while I was at it. The docs ([Environment variables](https://huggingface.co/docs/huggingface_hub/v0.21.4/package_reference/environment_variables#deprecated-environment-variables)) state that …
> hf_transfer for faster downloads

- README.md
@AlpinDale And here's a quick update for the docs to fit the updated docker stuff.
- Removed unnecessary quotes around `all`.
- We just changed the *internal* default port to 7860, so the command needs to reflect that on the right hand side of the `-p` flag.
- Removed unnecessary envvar `PORT` since the *host* port is determined by the left hand side of the `-p` flag.
- Removed unnecessary `-it` flags since we don't need an interactive terminal (for bash, etc.), we just run the app.
- Added `-d` to detach and keep the container running in the background without blocking the user's terminal.
- Replaced `--shm-size 10g` with `--ipc host`, just like we did in the Docker Compose file.
- Mentioned Docker Compose file.
A note about `--shm-size 10g` vs. `--ipc host`: Shared memory is usually in …
> docker-docs

- aphrodite/endpoints/openai/api_server.py
- examples/monitoring/prometheus.yaml
I have tested both api's (kobold already uses /metrics/) but please double check.
This api_server.py doesn't change any functionality, it's just to make the trailing slash explicit. 
prometheus.yaml fixes the constant HTTP 307 redirects it receives polling /metrics with no trailing slash.
prometheus_client expects a trailing slash in the url per the _use_gateway function and does HTTP redirect /metrics to /metrics/
[https://github.com/prometheus/client_python/blob/4535ce0f43097aa48e44a65747d82064f2aadaf5/prometheus_client/exposition.py#L592](https://github.com/prometheus/client_python/blob/4535ce0f43097aa48e44a65747d82064f2aadaf5/prometheus_client/exposition.py#L592
)
The trailing slash in that application appears to be correct per [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) …
> Explicit RFC3986 for prometheus_client asgi

- aphrodite/task_handler/model_runner.py
`seed` is a necessary, but not sufficient, condition for adding a generator to a seq.
The sampler currently trusts that the `generator` list matches the seqgroups in `RANDOM_SEED` exactly. Kinda fragile, but eh.
If a seqgroup that is decided to be `GREEDY` is also assigned a seed, they would previously get a generator, and the arrays would no longer line up, making everyone unhappy.
This change makes `RANDOM_SEED` the condition for getting a generator, only then asserting that there's a `seed` parameter.
> Fix fine-grained seeding.

- aphrodite/common/sequence.py
- aphrodite/modeling/layers/ops/rand.py
- aphrodite/modeling/layers/ops/sample.py
- aphrodite/modeling/layers/sampler.py
- aphrodite/modeling/sampling_metadata.py
- aphrodite/task_handler/model_runner.py
The triton kernels are currently unused, seem to break the seeded gens. Once it's fully utilized, it should offer some benefits:
- fused random and greedy sampling
- batched seeded sequences
We could also fuse logprobs if needed.
> feat: Triton kernels for sampling

- aphrodite/common/config.py
- aphrodite/engine/args_tools.py
- aphrodite/modeling/layers/attention/backends/flash_attn.py
- aphrodite/modeling/layers/attention/backends/xformers.py
- aphrodite/modeling/layers/attention/ops/paged_attn.py
- aphrodite/modeling/layers/sampler.py
- aphrodite/modeling/metadata.py
- aphrodite/processing/scheduler.py
- aphrodite/task_handler/model_runner.py
This PR is a part of a series of PRs to enable chunked prefill in aphrodite, mainly to save vram for large context sizes, and possibly speedup throughput. vLLM is currently employing a similar technique, so we will expand upon that. AFAIK, exllamav2 also has an efficient chunked decoding implementation.
Part 1 (here) addresses the shape of the query, changing it from 2D to 1D.
Part 2 will update the seqgroup metadata API.
Part 3 will need us to refactor the scheduler, by moving the logic for prefill scheduling and decoding scheduling to a dedicated function. We want a different scheduling policy for chunked prefill. Currently, we do prefill -> decoding, but when chunked, it should be decoding -> prefill.
Part 4 will add a separate scheduler for the chunked prefill
Part 5 will see it …
> Chunked Prefill Part 1

- aphrodite/modeling/layers/quantization/bitsandbytes.py
- aphrodite/modeling/models/cohere.py
It works, and I hacked the TieWordEmbedding. The loaded model size is the same, but I am still gettting less GPU blocks than 3b19fa02eae64f7d463d2b61f594aa6adbdf4057 (870 vs 1118)
> Fix cohere for command-r+

- aphrodite/endpoints/openai/api_server.py
Existing source attempts to pass a string as 'Prompt' to the tokenizer and performs a len() on a dict, returning the number of members and not the token count.
> Fix: kobold api /tokencount

- aphrodite/common/utils.py
From https://github.com/vllm-project/vllm/pull/4363
Tested to work for the stop button in SillyTavern.
> Abort requests when the connection to /v1/completions is interrupted.

- aphrodite/modeling/layers/linear.py
- aphrodite/modeling/models/gemma.py
- aphrodite/modeling/models/llama.py
- aphrodite/modeling/models/qwen2.py
- aphrodite/modeling/models/stablelm.py
Previous the weight shapes of `ColumnParallelLinear` are incorrect for q,k,v layers of some models, because the output size is divided by tp size twice.
> Fix linear bias of qkv layers in models.

- aphrodite/common/config.py
- aphrodite/engine/args_tools.py
- aphrodite/engine/output_processor/multi_step.py
- aphrodite/executor/cpu_executor.py
- aphrodite/executor/gpu_executor.py
- aphrodite/executor/ray_gpu_executor.py
- aphrodite/spec_decode/batch_expansion.py
- aphrodite/spec_decode/multi_step_worker.py
- aphrodite/spec_decode/ngram_worker.py
- aphrodite/spec_decode/spec_decode_worker.py
- aphrodite/spec_decode/top1_proposer.py
- aphrodite/spec_decode/util.py
- requirements-common.txt
Ngram prompt lookup decoding mode for speculative decoding, to enable draft-model-free speculative decoding.
Example usage:
```sh
aphrodite run meta-llama/Llama-2-7b-hf --speculative-model [ngram] --ngram-prompt-lookup-max 5 --ngram-prompt-lookup-min 1 --num-speculative-tokens 5 --use-v2-block-manager
```
> feat: ngram prompt lookup decoding

- aphrodite/endpoints/openai/protocol.py
- aphrodite/endpoints/openai/serving_chat.py
- aphrodite/endpoints/openai/serving_completions.py
Sterilize bias dict token range according to active model.
Now uses BiasLogitsProcessor tensors and all.
> Fix out-of-range token crash in OpenAI endpoint

- CMakeLists.txt
- aphrodite/modeling/layers/quantization/gguf.py
- build-linux-wheel.sh
- kernels/quantization/gguf/gguf_kernel.cu
- setup.py
Looks like sm_60 can't do dot product with 4 elements. There's a better solution, but this will work for now. I may implement an sm_60-only dot product function here.
resolves #413
> fix: restore backwards compatibility with sm_60 (P100 and GP100)

- .github/workflows/publish.yml
- CMakeLists.txt
- aphrodite/__init__.py
- pyproject.toml
- requirements-common.txt
- requirements-cpu.txt
- requirements-cuda.txt
- setup.py
This PR bumps the `torch` version to 2.3.0, `xformers` to `0.0.26.post1`, `triton` to `>=2.2.0`, and `flash-attn` optional dependency to `2.5.8`. 
resolves  #453
> Bump `torch` to 2.3.0

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- aphrodite/endpoints/openai/api_server.py
- docker/Dockerfile
As per the prometheus client docs, the app needs to be mounted on the parent app, not on the router.
Fixes #491
> openai: fix metrics endpoint

- cmake/utils.cmake
the error in question
```
[2/3] Building CUDA object CMakeFiles/_moe_C.dir/kernels/moe/softmax.cu.o
FAILED: CMakeFiles/_moe_C.dir/kernels/moe/softmax.cu.o
/usr/local/cuda-12.5/bin/nvcc -forward-unknown-to-host-compiler -DTORCH_EXTENSION_NAME=_moe_C -DUSE_C10D_GLOO -DUSE_C10D_NCCL -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -D_moe_C_EXPORTS -I/home/[USER]/aphrodite-engine/kernels -isystem /usr/include/python3.11 -isystem /tmp/pip-build-env-7xmj9w4y/overlay/lib/python3.11/site-packages/torch/include -isystem /tmp/pip-build-env-7xmj9w4y/overlay/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/cuda-12.5/include -DONNX_NAMESPACE=onnx_c2 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_dif …
```
> [bugfix] fix build issues on gcc 13.2

- README.md
When using the copy button this also copies the `$` so when it is pasted the commands are invalid.
> Remove `$` from the shell code blocks in README

- aphrodite/common/config.py
- aphrodite/modeling/layers/rotary_embedding.py
Seems like Llama 3.1 uses some weird trickery to extend the context past the original 8k to 131k. Since they don't specify the type in the config, we have to implicitly set the type to `extended` if the seqlen in the config is `131072`. We can get away with this because no other model AFAIK has that context length.
> feat: extended RoPE for Llama 3.1

- Dockerfile.openvino
- aphrodite/attention/backends/openvino.py
- aphrodite/attention/selector.py
- aphrodite/common/config.py
- aphrodite/common/utils.py
- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/args_tools.py
- aphrodite/engine/async_aphrodite.py
- aphrodite/executor/openvino_executor.py
- aphrodite/modeling/model_loader/openvino.py
- aphrodite/task_handler/openvino_model_runner.py
- aphrodite/task_handler/openvino_worker.py
- requirements-common.txt
- requirements-openvino.txt
- setup.py
- tests/benchmarks/throughput.py
Currently llama 3 produces garbage outputs. Will be fixed later.
```sh
docker build -f Dockerfile.openvino -t aphrodite-openvino .
docker run --ipc=host -p 2242:2242 -it --rm aphrodite-openvino
export APHRODITE_OPENVINO_KVCACHE_SPACE=100
export APHRODITE_OPENVINO_CPU_KV_CACHE_PRECISION=u8
export APHRODITE_OPENVINO_ENABLE_QUANTIZED_WEIGHTS=ON
aphrodite run NousResearch/Llama-2-7b-chat-hf --enable-chunked-prefill --max-num-batched-tokens 256
```
> feat: OpenVINO CPU backend

- aphrodite/attention/backends/flashinfer.py
- aphrodite/attention/selector.py
- aphrodite/task_handler/model_runner.py
Also enables CUDA support. Tested with flashinfer==0.0.7. See chart for performance:
TP=4 didn't seem to work with FlashInfer with the following error:
```console
RuntimeError: RuntimeError: Out of workspace memory in AlignedAlloactor
```
Will investigate later.
> Flashinfer for prefill phase

- aphrodite/endpoints/openai/api_server.py
- aphrodite/endpoints/openai/chat_utils.py
- aphrodite/endpoints/openai/protocol.py
- aphrodite/endpoints/openai/serving_chat.py
- aphrodite/endpoints/openai/serving_completions.py
- aphrodite/endpoints/openai/serving_tokenization.py
This PR lets us do things like this:
**Completions-style**:
```sh
$ curl -H "Content-Type: application/json" -d '{
"prompt": "This is a test prompt"
}' http://localhost:2242/v1/tokenize | jq .
```
Output:
```json
{
"tokens": [
2028,
374,
264,
1296,
10137
],
"count": 5,
"max_model_len": 131072
}
```
**Chat Completions-style**:
```sh
$ curl -H "Content-Type: application/json" -d '{
"messages": [
{"role": "user", "content": "Hi"}
]}' http://localhost:2242/v1/tokenize | jq .
```
Output:
```json
{
"tokens": [
128000,
128006,
882,
128007,
271,
13347,
128009,
128006,
78191,
128007,
271
],
"count": 11,
"max_model_len": 131072
}
```
**Detokenization**:
```sh
$ curl -H "Content-Type: application/json" -d '{
"tokens": [128000,128006,882,128007,271,13347,128009,128006,78191,128007,271]
}' …
```
> Chat Completions Tokenization endpoint

- CMakeLists.txt
- aphrodite/_custom_ops.py
- aphrodite/modeling/layers/sampler.py
- aphrodite/modeling/sampling_metadata.py
- aphrodite/spec_decode/draft_model_runner.py
- aphrodite/spec_decode/multi_step_worker.py
- kernels/ops.h
- kernels/prepare_inputs/advance_step.cu
- kernels/prepare_inputs/advance_step.cuh
- kernels/torch_bindings.cpp
This PR moves the implementation of `prepare_inputs` for `advance_step` (inside draft_model_runner.py) to GPU. It adds a new GPU kernel to modify prepare_inputs tensors on GPU directly, and also introduces some improvements to the sampler inside draft_model_runner to reduce unnecessary GPU<=>CPU overheads.
> move prepare_inputs to the GPU

- aphrodite/common/config.py
- aphrodite/endpoints/llm.py
- aphrodite/engine/args_tools.py
- aphrodite/modeling/models/utils.py
- aphrodite/task_handler/model_runner.py
This PR adds support for CPU offloading. Essentially, you can see this as virtually increasing the GPU memory size. e.g., if you have a 24 GiB GPU and set the `cpu_offload_gb` parameter to 10, it'll pad your GPU memory to 34 GiB. You can then load larger models.
You will need fast CPU<->GPU interconnect speeds, because we load the necessary parts of the model from CPU to GPU on the fly for each forward pass.
Model: Llama-2 13B @ FP16
GPU: RTX 4090
Offloaded: 5 GiB
Decode: 2.4 tok/s
> feat: add CPU offloading support

- aphrodite/modeling/layers/activation.py
- aphrodite/modeling/layers/rotary_embedding.py
- aphrodite/modeling/models/__init__.py
- aphrodite/modeling/models/nemotron.py
- requirements-common.txt
I tried adding kernels for ReLU and ReLU squared, but they didn't do any better than `torch.nn.ReLU()` so let's leave it at this.
> feat: add nemotron HF support

- aphrodite/endpoints/cli.py
- config.yaml
Allow users to write a YAML config file and use that to launch the engine with all the options pre-configured. Usage:
```sh
aphrodite yaml config.yaml
```
I've included a sample config.yaml file to get users started, along with detailed explanation for each option.
> feat: add yaml config parsing

- aphrodite/common/sequence.py
- aphrodite/common/utils.py
- aphrodite/endpoints/openai/api_server.py
- aphrodite/endpoints/openai/args.py
- aphrodite/endpoints/openai/logits_processors.py
- aphrodite/endpoints/openai/rpc/__init__.py
- aphrodite/endpoints/openai/rpc/client.py
- aphrodite/endpoints/openai/rpc/server.py
- aphrodite/endpoints/openai/serving_chat.py
- aphrodite/endpoints/openai/serving_completions.py
- aphrodite/endpoints/openai/serving_embedding.py
- aphrodite/endpoints/openai/serving_engine.py
- aphrodite/endpoints/openai/serving_tokenization.py
- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/async_aphrodite.py
- aphrodite/engine/metrics.py
- aphrodite/engine/output_processor/interfaces.py
- aphrodite/engine/protocol.py
- aphrodite/executor/distributed_gpu_executor.py
- aphrodite/executor/ray_tpu_executor.py
- aphrodite/executor/ray_xpu_executor.py
- aphrodite/transformers_utils/tokenizer_group/__init__.py
- aphrodite/transformers_utils/tokenizer_group/base_tokenizer_group.py
- aphrodite/transformers_utils/tokenizer_group/tokenizer_group.py
Currently, the OpenAI API server and AsyncAphrodite share the same asyncio event loop. This means that the API server and the CPU components of the AsyncAphrodite contend for the same resources.
Enable better overlapping of the API server and AsyncAphrodite via multiprocessing by spitting into two processes that communicate over gRPC with protobufs. This is roughly the architecture used by vLLM and TGI (though TGI has more items in the server than we are proposing here).
- Write protobuf API to roughly match AsyncAphrodite generate() method, separate API server into separate process and measure the speedup
- Will exclude LogitsProcessors - it’s agreed that these don’t belong in SamplingParams anyhow. Instead we’ll include the corresponding external API parameters e.g. for guided decoding …
> feat: add RPC server and client via ZMQ

- aphrodite/engine/output_processor/single_step.py
`python tests/benchmarks/engine/throughput.py --model EleutherAI/pythia-70m --input-len 256 --output-len 256 --num-prompts 1000`
PR: 
```
Throughput: 43.03 requests/s, 22031.91 tokens/s
Throughput: 42.53 requests/s, 21775.44 tokens/s
Throughput: 42.86 requests/s, 21944.34 tokens/s
```
rc_054:
```
Throughput: 41.74 requests/s, 21371.12 tokens/s
Throughput: 42.00 requests/s, 21502.24 tokens/s
Throughput: 41.30 requests/s, 21143.94 tokens/s
```
> chore: simplify output processing with shortcut for non-parallel sampling and non-beam search usecase

- aphrodite/attention/selector.py
- aphrodite/common/utils.py
> fix: default api port and attention selector

- aphrodite/common/utils.py
- aphrodite/endpoints/openai/rpc/client.py
- aphrodite/endpoints/openai/serving_chat.py
- aphrodite/endpoints/openai/serving_completions.py
- aphrodite/endpoints/openai/serving_embedding.py
- aphrodite/engine/async_aphrodite.py
- aphrodite/engine/protocol.py
To resolve a few issues:
- Abort logic is missing for streaming chat requests - these continue to run after the client disconnects
- For multi-prompt completion requests, only one of the `n` running sequences actually gets aborted
- Cancelled requests that are queued will still be pre-filled before getting aborted
- Some of the existing async generator logic may be contributing to clean-shutdown garbage collection issues
We will:
- Use native asyncio task/generator cancellation propagation as much as possible. This includes making use of explicitly cancellable async generators (via `asyncio.aclose()`) rather than async iterators in most cases
- Re-implement `merge_async_iterators` to encapsulate polling for disconnection, even before any results have been produced (while the request is …
> fix: better async request cancellation

- aphrodite/endpoints/chat_utils.py
- aphrodite/endpoints/openai/protocol.py
- aphrodite/endpoints/openai/serving_chat.py
- aphrodite/endpoints/openai/serving_tokenization.py
- aphrodite/transformers_utils/tokenizer.py
As of transformers v44.4, there's no default chat template
> fix: gracefully handle missing chat template

- aphrodite/endpoints/openai/api_server.py
This was somehow being passed to the model config anyway, and causing weird issues where we had bf16 models casted to fp16, then re-casted to bf16.
> fix: hardcoded float16 in embedding mode check

- aphrodite/lora/models.py
Scale `alpha` value by `sqrt(r)` if `use_rslora` is in config.
> fix: RSLoRA support

- aphrodite/endpoints/openai/api_server.py
- aphrodite/endpoints/openai/rpc/client.py
If there's an init error with the MP server, the client will hang.
> fix: multiprocessing timeout

- aphrodite/common/utils.py
To retain backwards compatibility.
> fix: make `merge_async_iterators.is_cancelled()` optional

- aphrodite/endpoints/openai/api_server.py
- aphrodite/endpoints/openai/rpc/client.py
- aphrodite/endpoints/openai/rpc/server.py
- aphrodite/engine/async_aphrodite.py
- aphrodite/server/launch.py
If the engine is errored, and the user pings /health, this will also kill the API server.
> fix: kill api server when pinging dead engine

- aphrodite/processing/block/naive_block.py
- aphrodite/processing/block/prefix_caching_block.py
If prefix caching is enabled, and the blocks are swapped out, the left-over caches will be in the evictor group if there are no references. In the meantime, the cache blocks will be evicted, for example, 2 out of 10 cached blocks. Let's say the remaining 8 blocks in the evictor are the last available blocks in the allocator, and the sequence wants to swapped in, the free blocks will count as 8. The touched blocks is calculated as 2, which is incorrect because the cache is not shared by any other blocks. In this case the correct touched blocks should be 10, and can't swap in. In the regular case, if the lookahead slots are more than the free slots, it first need to occupy the block containing the free slots, then plus the remaining required blocks.
> fix: `get_num_blocks_touched` logic

- aphrodite/attention/backends/flash_attn.py
- aphrodite/attention/backends/utils.py
- aphrodite/common/block.py
- aphrodite/common/outputs.py
- aphrodite/common/sequence.py
- aphrodite/common/utils.py
- aphrodite/modeling/__init__.py
- aphrodite/modeling/sampling_metadata.py
- aphrodite/processing/block_manager_v1.py
- aphrodite/processing/scheduler.py
- aphrodite/task_handler/model_runner.py
Huge speedup;
- Avoid python object allocations for `InterDataForSeqGroup` objects/ These objects have lot of fields, and most of the them were allocated dynamically. In this PR, these objects are pre-allocated and reused between runs. The pre-allocation is done per "number of sequences per group" (to support beam search), where most of the time we simply have one sequence per group.
- Avoid python object allocations for `SequenceGroupMetadata` inside scheduler, in the same way as for (1).
- Avoid python object allocations for `SequenceGroupToSample` inside `SamplingMetadata.prepare(...)`
- Add an optimization to scheduler to be aware of "one sequence per group" case (since most of them we do not run beam search).
- A bunch of misc small stuff to reduce object allocations
1xA40, …
> optimization: reduce end-to-end overhead from python obj allocation

- aphrodite/attention/backends/rocm_flash_attn.py
- aphrodite/attention/backends/xformers.py
- aphrodite/attention/ops/ipex_attn.py
- aphrodite/attention/ops/paged_attn.py
- aphrodite/attention/ops/prefix_prefill.py
- aphrodite/common/config.py
> feat: enable using fp8 kv and prefix caching with chunked prefill

- aphrodite/engine/async_aphrodite.py
Avoid unnecessarily enqueuing of a final message after an exception and avoid aborting requests in the engine that were never started.
Follow-up to #641
> chore: better stream termination in async engine

- aphrodite/attention/backends/utils.py
If there's more than 256 elements, use numpy implementation. Otherwise, python to avoid numpy overhead.
> feat: add numpy implementation of `compute_slot_mapping`

- aphrodite/processing/block/block_table.py
Fixes IndexError when using v2 block manager + chunked prefill. Only happens during the last chunk, and if prompt_tokens length is a multiple of block size.
> fix: chunked prefill with v2 block manager

- kernels/core/scalar_type.hpp
- kernels/quantization/gptq_marlin/gptq_marlin.cu
Use `ScalarType` instead of `num_bits` (in combination with `has_zp`) to preform the dispatching for `gptq_marlin` this sets the stage for folding `fp8_marlin.cu` into `gptq_marlin.cu` since now we can move `dequant_8bit` in `fp8_marlin.cu` as a `dequant<T, vllm::kFE4M3fn.id()>(int q)` specialization. I did not fold `fp8_marlin.cu` into `gptq_marlin.cu` in this PR to avoid excessive compile times for `gptq_marlin.cu` for now.
In-order to support passing scalar type as a template parameter in C++17, it has to be serialized to something that can be passed as a template parameter. This per introduces the concept of serializing the type into a 64 bit int `id` (that can be passed as a parameter) alongside a deserialization routine (`from_id` if the template needs to access the traits of the …
> chore: use scalar type to dispatch to different `gptq_marlin` kernels

- aphrodite/modeling/layers/linear.py
- aphrodite/modeling/parameter.py
- aphrodite/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
- aphrodite/quantization/gptq_marlin.py
Also adds `PackedColumnParameter` to support packed parameters without row parallelism
> chore: migrate gptq_marlin to AphroditeParameters

- aphrodite/engine/args_tools.py
- aphrodite/executor/neuron_executor.py
- aphrodite/task_handler/neuron_model_runner.py
- aphrodite/task_handler/neuron_worker.py
Mainly because of Neuron, because it needs `block_size = seq_len`
> chore: add support for up to 2048 block size

- aphrodite/transformers_utils/detokenizer.py
An issue introduced in #599, where I forgot the return statement for  the `decode_sequence_inplace` function. This resulted in stop strings being ignored.
> chore: fix return statement in `Detokenizer.decode_sequence_inplace`

- aphrodite/distributed/device_communicators/cuda_wrapper.py
Steps to reproduce:
1. Pull the docker image [nvidia/cuda:12.0.1-devel-ubuntu20.04](https://hub.docker.com/r/nvidia/cuda/) (I did it with a vast.ai server)
2. Pull the aphrodite source and run `./update_runtime.sh`
3. Run `./runtime aphrodite run model -tp 2`
4. The engine stucks at `generating GPU P2P access cache `
This only happens at some specific version of pytorch and only when you try to use tensor paralellism.
Reference issue: https://github.com/vllm-project/vllm/issues/6893
Fix comment: https://github.com/vllm-project/vllm/issues/6893#issuecomment-2255377709
Equivalent PR in vllm: https://github.com/vllm-project/vllm/pull/7127
> Fix tensor parallelism, libcudart path for some versions of pytorch

- aphrodite/lora/ops/bgmv_expand.py
- aphrodite/lora/ops/bgmv_expand_slice.py
- aphrodite/lora/ops/bgmv_shrink.py
- aphrodite/lora/ops/sgmv_expand.py
- aphrodite/lora/ops/sgmv_expand_slice.py
- aphrodite/lora/ops/sgmv_shrink.py
This effectively locks us to torch 2.4.0
> chore: register lora functions as torch ops

- aphrodite/common/config.py
- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/args_tools.py
- aphrodite/executor/cpu_executor.py
- aphrodite/executor/executor_base.py
- aphrodite/executor/gpu_executor.py
- aphrodite/executor/openvino_executor.py
- aphrodite/executor/ray_xpu_executor.py
- aphrodite/executor/tpu_executor.py
- aphrodite/executor/xpu_executor.py
- aphrodite/inputs/registry.py
- aphrodite/modeling/model_loader/__init__.py
- aphrodite/modeling/model_loader/loader.py
- aphrodite/modeling/models/__init__.py
- aphrodite/multimodal/registry.py
- aphrodite/spec_decode/draft_model_runner.py
- aphrodite/spec_decode/target_model_runner.py
- aphrodite/task_handler/cpu_model_runner.py
- aphrodite/task_handler/cpu_worker.py
- aphrodite/task_handler/embedding_model_runner.py
- aphrodite/task_handler/enc_dec_model_runner.py
- aphrodite/task_handler/model_runner.py
- aphrodite/task_handler/tpu_model_runner.py
- aphrodite/task_handler/tpu_worker.py
- aphrodite/task_handler/utils.py
- aphrodite/task_handler/worker.py
- aphrodite/task_handler/xpu_model_runner.py
Previously we initialize `MultiModalConfig` for all models regardless of whether or not the model itself is multi-modal. This can cause some developer confusion. This PR refactors the logic and make `MultiModalConfig` an attribute of `ModelConfig` to make the separation cleaner.
> chore: refactor `MultiModalConfig` initialization and profiling

- .github/workflows/deploy.yml
Adds forzen-lockfile option, as it's recommended in CI environments to prevent dep version discrepancy with local setup.
> ci: fix dep install using pnpm

- CMakeLists.txt
- aphrodite/_custom_ops.py
- aphrodite/common/config.py
- aphrodite/engine/args_tools.py
- aphrodite/quantization/__init__.py
- aphrodite/quantization/fp6.py
- aphrodite/quantization/utils/fp6_utils.py
- kernels/quantization/fp6/configs.h
- kernels/quantization/fp6/fp6_linear.cu
- kernels/quantization/fp6/kernel_matmul.cuh
- kernels/quantization/fp6/kernel_reduction.cuh
- kernels/quantization/fp6/ptx_cp.async.cuh
- kernels/quantization/fp6/ptx_mma.cuh
- kernels/quantization/fp6/utils_core.cuh
- kernels/quantization/fp6/utils_gmem.cuh
- kernels/quantization/fp6/utils_parallel_dequant.cuh
- kernels/quantization/quant_ops.h
- kernels/torch_bindings.cpp
- tests/benchmarks/engine/throughput.py
Based on #617 by @intervitens
**TL;DR** load an FP16 model in bit sizes between 2 and 7: `aphrodite run <your model> -q fp4` for example.
This PR adds support for online (on-the-fly, runtime) quantization of FP16 models to FP2, FP3, FP4, FP5, FP6, and FP7. Unlike DeepSpeedFP, this method is actually fast and has a wider range of hardware support.
Does not need to load the model in FP16 first before quantization, unlike `-q fp8` and DeepSpeedFP.
For more fine-grained control over the data type, you can specify the exponent to use:
`-q quant_llm -quant-llm-fp-bits {2,3,4,5,6,7} --quant-llm-exp-bits {1,2,3,4,5}`
The heuristic used for determining the mantissa value is `weight_bits - exp_bits - 1`. Make sure your provided values are valid based on that, and should not result in a negative …
> feat: quant_llm support

- aphrodite/modeling/layers/sampler.py
Fixes a crash from token bans during batched inference. Has been running stable for the past few hours and token bans seem to still work.
> Fix for a crash from token bans

- aphrodite/transformers_utils/tokenizers/mistral.py
Mistral tokenizer does not support `skip_special_tokens=False`. We currently had an assertion for this that would crash the engine if that param was set to False. This fixes it by demoting it to a `logger.error()`, and fixes the incorrect error message.
> fix: demote skip_special_tokens assertion to logger error

- aphrodite/endpoints/openai/api_server.py
Windows seems to read the file with the default `charmap` encoding (`cp1252`), so we have to force UTF-8.
> fix: kobold lite embedded UI on windows

- aphrodite/endpoints/openai/api_server.py
v0.2 update: make full paths optional (due to security concerns), use relative (incomplete) paths instead.
> feat: update to serviceinfo v0.2

- aphrodite/modeling/layers/sampler.py
Temperature was broken because of the `.to(torch.float)` upcast making a copy and thus not modifying `logits` inline.
The rest addresses the ultra-low-temp overflow that the upcast was trying to fix in the first place.
For discussion:
1. This _should_ be safe. Is it? A sampler relying on exact logit magnitudes seems insane to me.
2. I'm only partly convinced by the [-inf, 1] range. Using [-inf, 0] would drop from 75% to 50% of available values, but simultaneously places the very highest precision at the top logits.
> fix: temperature issues

- tests/samplers/test_sampler.py
Transformer update broke some stuff, specifically the `_get_logits_warper` method of GenerationMixin().
> fix: sampler test with new transformers version

- CMakeLists.txt
- aphrodite/_custom_ops.py
- aphrodite/modeling/layers/sampler.py
- kernels/ops.h
- kernels/sampling/math.cuh
- kernels/sampling/sampling.cu
- kernels/sampling/sampling.cuh
- kernels/sampling/utils.cuh
- kernels/sampling/vec_dtypes.cuh
- kernels/torch_bindings.cpp
- tests/benchmarks/engine/throughput.py
Is faster than Flashinfer's, at least. Still rather disappointing.
Baseline:
```
Processed prompts: 100%|████████████| 2048/2048 [01:07<00:00, 30.51it/s, est. speed input: 31208.74 toks/s, output: 3904.91 toks/s]
Throughput: 29.51 requests/s, 33996.89 tokens/s
```
PR:
```
Processed prompts: 100%|████████████| 2048/2048 [01:07<00:00, 30.20it/s, est. speed input: 30892.24 toks/s, output: 3865.30 toks/s]
Throughput: 29.22 requests/s, 33660.42 tokens/s
```
Flashinfer:
```
Processed prompts: 100%|██████| 2048/2048 [01:07<00:00, 30.16it/s, est. speed input: 30853.63 toks/s, output: 3860.47 toks/s]
Throughput: 29.19 requests/s, 33631.21 tokens/s
```
> feat: add cuda sampling kernels for top_k and top_p

- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/metrics.py
- aphrodite/engine/metrics_types.py
- aphrodite/processing/block/common.py
- aphrodite/processing/block/cpu_gpu_block_allocator.py
- aphrodite/processing/block/interfaces.py
- aphrodite/processing/block/naive_block.py
- aphrodite/processing/block/prefix_caching_block.py
- aphrodite/processing/block_manager_v1.py
- aphrodite/processing/block_manager_v2.py
- aphrodite/processing/evictor_v2.py
- aphrodite/processing/interfaces.py
- aphrodite/processing/placeholder_block_space_manager.py
- aphrodite/processing/scheduler.py
- tests/core/block/test_prefix_caching_block.py
- tests/prefix_caching/test_prefix_caching.py
> feat: add metrics for prefix cache hit rate

- aphrodite/engine/aphrodite_engine.py
Forgot to assign the tokenizer for when we're *not* skipping the tokenizer initialization. This caused speculative decoding and multi-step (WIP) to break.
> fix: unbound tokenizer error

- aphrodite/common/config.py
- aphrodite/quantization/awq_marlin.py
AWQ Marlin kernels currently have an issue that needs a bit more focus from me to solve. Temporarily disabling the serialization to awq_marlin.
> fix: disable awq_marlin override for awq models

- aphrodite/common/sampling_params.py
- aphrodite/endpoints/openai/protocol.py
- aphrodite/modeling/layers/sampler.py
- aphrodite/modeling/sampling_metadata.py
- tests/samplers/test_sampler.py
Another PR in the DRY saga. This one adds a range.
- 0 (default): All tokens are considered for penalization (input + output)
- \>0: Only the `dry_range` tokens are considered, counted from right to left.
- <0: Invalid.
Added a test case for DRY as well.
> sampler: add range parameter for DRY

- requirements-build.txt
The Machete kernel generator script requires jinja2.
> build: add jinja2 to requirements file

- aphrodite/modeling/layers/sampler.py
Upgraded from extremely slow to pretty slow.
Possible issues:
- Calculating the padding around ln 642 seems dumb, surely we have that somewhere?
- Suspect the ln 681 loop is where the slowness is coming from now, but I'm not sure. Also not sure how to tensorize it atm.
> Rewrite DRY sampler to be a lot faster

- aphrodite/modeling/layers/sampler.py
Potentially causing slowdowns due to logger spams.
> fix: temp_last warning being repeated for every output token

- aphrodite/modeling/sampling_metadata.py
A potential fix for:
```
File "/home/ubuntu/aphrodite-engine/aphrodite/modeling/layers/sampler.py", line 148, in forward
self._init_sampling_tensors(logits, sampling_metadata)
File "/home/ubuntu/aphrodite-engine/aphrodite/modeling/layers/sampler.py", line 112, in _init_sampling_tensors
) = SamplingTensors.from_sampling_metadata(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/aphrodite-engine/aphrodite/modeling/sampling_metadata.py", line 600, in from_sampling_metadata
sampling_tensors = SamplingTensors.from_lists(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/aphrodite-engine/aphrodite/modeling/sampling_metadata.py", line 793, in from_lists
dry_sequence_breakers_t = torch.tensor(
^^^^^^^^^^^^^
ValueError: expected sequence of length 4 at dim 1 (got 5)
```
> sampler: pad dry sequence breakers tensor

- aphrodite/endpoints/openai/api_server.py
- aphrodite/server/launch.py
- tests/endpoints/openai/test_mp_api_server.py
Before:
```
Process SpawnProcess-1:
Traceback (most recent call last):
File "/home/ubuntu/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/home/ubuntu/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.11/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/home/ubuntu/aphrodite-engine/aphrodite/endpoints/openai/rpc/server.py", line 198, in run_rpc_server
server = AsyncEngineRPCServer(async_engine_args, rpc_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/aphrodite-engine/aphrodite/endpoints/openai/rpc/server.py", line 35, in __init__
self.engine = AsyncAphrodite.from_engine_args(async_engine_args) …
```
> api: better startup failure UX

- CMakeLists.txt
- kernels/quantization/machete/machete_pytorch.cu
The instruction set used here was introduced in cuda 12.
> kernel: do not compile machete for cuda 11 and below

- aphrodite/spec_decode/batch_expansion.py
- aphrodite/spec_decode/spec_decode_worker.py
- aphrodite/spec_decode/util.py
- tests/spec_decode/test_utils.py
Should provide a small boost to spec decode throughput at low bsz.
vllm-project/vllm#7851
> spec decode: streamline batch expansion tensor manipulation

- aphrodite/endpoints/openai/serving_embedding.py
- examples/openai_api/embedding.py
- tests/endpoints/openai/test_embedding.py
To align with OpenAI python library behavior.
> api: use fp32 for base64 embeddings

- aphrodite/common/config.py
- aphrodite/common/envs.py
- aphrodite/common/sampling_params.py
- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/args_tools.py
- aphrodite/task_handler/model_runner.py
- aphrodite/task_handler/worker.py
Launching with `--single-user-mode` or `single_user_mode=True` will have the worker only allocate enough memory for a single sequence. This overrides the `gpu_memory_utilization` (`-gmu`) value, and will implicitly set `max_num_seqs=1`.
> feat: add single user mode

- aphrodite/endpoints/openai/api_server.py
- aphrodite/modeling/model_loader/weight_utils.py
When using inline loading, if your target model contains an `aphrodite_config.yaml` file, whether local or on HF, it'll use that for the launch params. Otherwise, falls back to default launch values.
> api: support aphrodite_config.yaml with inline loading

- aphrodite/modeling/guided_decoding/lm_format_enforcer_logits_processors.py
- requirements-common.txt
When starting a generation using Mistral Large 2411 (or 2407) with `--tokenizer-mode mistral` set, the generation fails and an error is thrown: `TypeError: SentencePieceTokenizer.encode() missing 2 required positional arguments: 'bos' and 'eos'`. The stack trace points to the guided decoding processor.
Tweaking `aphroditeLogitsProcessor#build_aphrodite_token_enforcer_tokenizer_data` to match the latest version of [lm-format-enforcer's vllm implementation](https://github.com/noamgat/lm-format-enforcer/blob/main/lmformatenforcer/integrations/vllm.py#L35-L46), with a MistralTokenizer case and passing `vocab_size` into `build_token_enforcer_tokenizer_data`, appears to fix this issue.
> Fix SentencePieceTokenizer error when generating on Mistral Large 2411 with `--tokenizer-mode mistral`

- aphrodite/endpoints/openai/api_server.py
- tests/benchmarks/engine/throughput.py
Synchronous engine (`AphroditeEngine`):
```
Throughput: 58.89 requests/s, 15075.27 tokens/s
```
Asynchronous engine (`AsyncAphrodite`):
```
Throughput: 24.50 requests/s, 6271.73 tokens/s
```
😭
> benchmarks: add `--async-engine` arg to throughput benchmark

- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/async_aphrodite.py
- aphrodite/processing/scheduler.py
- aphrodite/worker/multi_step_model_runner.py
Under high loads, the engine is supposed to swap requests. This mechanism was broken with the introduction of async post-processing. This PR fixes that.
> core: fix async postprocessor in case of preemption

- Dockerfile
- Dockerfile.cpu
- Dockerfile.neuron
- Dockerfile.openvino
- Dockerfile.ppc64le
- Dockerfile.tpu
- Dockerfile.xpu
- aphrodite/assets/video.py
- aphrodite/modeling/models/__init__.py
- aphrodite/modeling/models/llava_next_video.py
- aphrodite/multimodal/registry.py
- aphrodite/multimodal/utils.py
- aphrodite/multimodal/video.py
- aphrodite/transformers_utils/image_processor.py
- requirements-common.txt
- tests/conftest.py
- tests/models/test_llava_next_video.py
> vlm: add support for video modality + llava next video model

- tests/spec_decode/e2e/conftest.py
- tests/spec_decode/e2e/test_eagle_correctness.py
- tests/spec_decode/e2e/test_integration.py
- tests/spec_decode/e2e/test_integration_dist_tp2.py
- tests/spec_decode/e2e/test_integration_dist_tp4.py
- tests/spec_decode/e2e/test_logprobs.py
- tests/spec_decode/e2e/test_medusa_correctness.py
- tests/spec_decode/e2e/test_mlp_correctness.py
- tests/spec_decode/e2e/test_multistep_correctness.py
- tests/spec_decode/e2e/test_ngram_correctness.py
- tests/spec_decode/e2e/test_seed.py
Now all of them pass, and we can move on to removing --worker-use-ray/--engine-use-ray
> tests: refactor speculative decoding tests to remove the async engine

- .github/ISSUE_TEMPLATE/400-bug-report.yml
- aphrodite/worker/model_runner.py
- aphrodite/worker/model_runner_base.py
- tests/basic_correctness/test_basic_correctness.py
This PR allows the model runner to dump a pickle file, in case there's an error too obscure for the traceback, e.g. an illegal memory access. Issue template for bug reporting has been updated as well.
> core: dump model runner inputs during crash

- aphrodite/modeling/sampling_metadata.py
This little oversight was causing output quality to tank.
```sh
aphrodite run NousResearch/Meta-Llama-3.1-8B-Instruct --max-model-len 2048 -tp 2 --enable-chunked-prefill --enable-prefix-caching --max-seq-len-to-capture 2048
```
```sh
lm_eval --model local-completions --tasks gsm8k --model_args model="NousResearch/Meta-Llama-3.1-8B-Instruct",base_url=http://localhost:2242/v1/completions,num_concurrent=256,max_retries=3,tokenized_requests=False
```
Main:
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|-----|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.0099|±  |0.0027|
|     |       |strict-match    |     5|exact_match|↑  |0.0000|±  |0.0000|
PR:
|Tasks|Version|     Filter     |n-shot| …
> fix: add missing logit index increment in sampling metadata prep

- aphrodite/distributed/device_communicators/shm_broadcast.py
Small security concern, don't want to expose to all interfaces.
> distributed: bind only to 127.0.0.1 for local-only usage

- aphrodite/modeling/models/llava_next.py
Incorrect feature size with an image of 700x840 size
> vlm: fix feature size calculation for llava-next models

- aphrodite/common/sampling_params.py
- aphrodite/endpoints/openai/protocol.py
- aphrodite/modeling/layers/sampler.py
- aphrodite/modeling/sampling_metadata.py
PR:
```
Starting: Batch 1 (20 requests without dry_multiplier)
Batch 1 (20 requests without dry_multiplier): Completed 20 requests in 14.64 seconds
Starting: Batch 2 (10/20 requests with dry_multiplier)
Batch 2 (10/20 requests with dry_multiplier): Completed 20 requests in 19.11 seconds
Starting: Batch 3 (20 requests with dry_multiplier)
Batch 3 (20 requests with dry_multiplier): Completed 20 requests in 23.49 seconds
Total execution time for all batches: 57.24 seconds
```
Main:
```
Starting: Batch 1 (20 requests without dry_multiplier)
Batch 1 (20 requests without dry_multiplier): Completed 20 requests in 14.69 seconds
Starting: Batch 2 (10/20 requests with dry_multiplier)
Batch 2 (10/20 requests with dry_multiplier): Completed 20 requests in 26.89 seconds
Starting: Batch 3 (20 requests …
```
> samplers: improved DRY performance

- aphrodite/common/envs.py
- aphrodite/modeling/_custom_op.py
- aphrodite/modeling/layers/activation.py
- aphrodite/modeling/layers/layernorm.py
- aphrodite/modeling/layers/ops/layernorm.py
- aphrodite/modeling/layers/rotary_embedding.py
- tests/kernels/test_layernorm.py
First in a series of PRs to add Triton alternatives to every single crucial Cuda kernel in Aphrodite. This only includes the kernels required to run the engine with a normal un-quantized (b)float16 model. Quantization is currently available through AWQ, but other methods aren't currently prioritized.
This PR adds support for the layernorm layer, with no performance loss:
2x A6000, Llama 3.1 8B, 1000 prompts, 512 input, 512 output
```sh
export APHRODITE_USE_TRITON_LAYERNORM=1
```
**Cuda:**
```
Processed prompts: 100%|█| 1000/1000 [05:30<00:00,  3.03it/s, est. speed input: 1550.34 toks/s, output: 1550.34 toks/s]
```
**Triton:**
```
Processed prompts: 100%|█| 1000/1000 [05:30<00:00,  3.03it/s, est. speed input: 1550.49 toks/s, output: 1550.49 toks/s]
```
The current triton kernels for …
> (1/N) Triton Backend: integrate Triton layernorm kernels

- aphrodite/common/envs.py
- aphrodite/common/utils.py
- aphrodite/modeling/_custom_op.py
- aphrodite/modeling/layers/activation.py
- aphrodite/modeling/layers/ops/activation.py
- aphrodite/modeling/layers/ops/layernorm.py
- aphrodite/modeling/layers/ops/utils.py
- tests/kernels/test_activation.py
Follow-up to #1125 
This PR adds activation kernels. Some of the geglu and swiglu kernel code is borrowed from [Unsloth](https://github.com/unslothai/unsloth)
TODOs:
> (2/N) Triton Backend: integrate Triton activation kernels

- aphrodite/common/envs.py
- aphrodite/engine/multiprocessing/__init__.py
- aphrodite/engine/multiprocessing/client.py
- aphrodite/engine/multiprocessing/engine.py
- tests/mq_aphrodite_engine/test_error_handling.py
The heartbeat runs on a separate thread so it's not queued behind other requests.
> API: use heartbeats instead of health checks

- aphrodite/endpoints/openai/serving_chat.py
Fixes reported numbers for mllama
> fix: include encoder prompt len to non-stream api usage response

- aphrodite/endpoints/chat_utils.py
- aphrodite/endpoints/llm.py
- aphrodite/endpoints/openai/protocol.py
- aphrodite/endpoints/openai/serving_chat.py
- aphrodite/endpoints/openai/serving_tokenization.py
- tests/endpoints/openai/test_chat_template.py
- tests/endpoints/openai/test_tokenization.py
Adding `continue_final_message=True` in the request with a the final message in the conversation being the assistant's turn will remove EOS and attempt to continue instead.
> api: add support for prefill to chat completions endpoint

- aphrodite/endpoints/openai/protocol.py
- aphrodite/endpoints/openai/serving_chat.py
- aphrodite/endpoints/openai/serving_completions.py
- aphrodite/endpoints/openai/serving_embedding.py
- aphrodite/engine/args_tools.py
- aphrodite/engine/async_aphrodite.py
- aphrodite/engine/multiprocessing/__init__.py
- aphrodite/engine/multiprocessing/client.py
- aphrodite/engine/protocol.py
- tests/benchmarks/engine/prioritization.py
If `--scheduling-policy priority` is set at launch, requests containing a `priority` parameter with a value larger than 0 (default) will be prioritized. 1 means the highest priority, and ascending numbers will have a lower priority in the queue. Requests with 0 (default) will be treated in a FIFO (first-in first-out) fashion.
> api: expose priority scheduling in the API server

- aphrodite/common/envs.py
- aphrodite/engine/aphrodite_engine.py
- aphrodite/engine/metrics.py
- aphrodite/engine/metrics_types.py
- aphrodite/engine/multiprocessing/client.py
By exporting `APHRODITE_REQUEST_LEVEL_METRICS=1`, the engine will log metrics on a per-request basis, instead of interval-based.
> feat: add request-level logging

- aphrodite/common/config.py
- aphrodite/engine/args_tools.py
- aphrodite/processing/interfaces.py
V1 will be deprecated soon. If users want to use V1 still, they can set `--use-v2-block-manager=False`.
> core: make v2 block manager the default

- aphrodite/common/sampling_params.py
- aphrodite/endpoints/openai/protocol.py
- aphrodite/modeling/layers/sampler.py
Ban a specific token across a range of output tokens, e.g.:
```sh
"token_ban_ranges": [
[[7762, 7763], 0, 10]
]
```
This bans tokens 7762 and 7763, starting from the first token (0), all the way to the 10th output token.
The input type is:
```py
token_ban_ranges: List[Tuple[List[int], int, int]]
```
Where the `List[int]` is the list of tokens to ban, the first `int` is the starting position in the output (0=start), and the second `int` is the number of tokens to consider after the starting position.
> sampler: add option to ban tokens within a specific range of output tokens

- aphrodite/_custom_ops.py
Use `impl_abstract` if `register_fake` is unavailable (older torch versions)
> fix: handle older torch versions in fake ops registration

- aphrodite/lora/fully_sharded_layers.py
- aphrodite/lora/layers.py
Handle cases where all three lora_a in `MergedQKVParallelLinearWithShardedLora` could be None
> fix: fully sharded lora bug

- =3.26
- Dockerfile.cpu
- aphrodite/modeling/layers/linear.py
- aphrodite/quantization/__init__.py
- aphrodite/quantization/awq_marlin.py
- aphrodite/quantization/ipex_quant.py
- aphrodite/worker/cpu_worker.py
Very slow for large models. 8B AWQ takes about 5000 seconds to process 4 input tokens and 128 output tokens, end-to-end.
Tested on a CPU with AVX2. AVX512 is expected to perform much better.
> CPU: add support for AWQ quants (slow)

- aphrodite/engine/multiprocessing/client.py
> fix: invalid args passed to `_process_request` in `encode()`

- aphrodite/common/envs.py
- aphrodite/common/sequence.py
- aphrodite/compilation/backends.py
- aphrodite/compilation/compile_context.py
- aphrodite/compilation/decorators.py
- aphrodite/compilation/levels.py
- aphrodite/compilation/wrapper.py
- aphrodite/modeling/_custom_op.py
- aphrodite/modeling/models/gemma2.py
- aphrodite/modeling/models/llama.py
- aphrodite/modeling/models/llava.py
- aphrodite/modeling/models/qwen2.py
- aphrodite/platforms/tpu.py
- aphrodite/plugins/__init__.py
- aphrodite/quantization/vptq.py
- aphrodite/worker/model_runner.py
- aphrodite/worker/tpu_model_runner.py
- tests/compile/test_wrapper.py
We now should have full control over the compilation process, instead of just entrusting all to `torch.compile`.
Currently, we have 5 levels. Use the `APHRODITE_TORCH_COMPILE_LEVEL` flag to trigger each:
- **`0` (`NO_COMPILATION`)**: No compilation; normal Aphrodite.
- **`1` (`DYNAMO_AS_IS`)**: The model is directly passed to `torch.compile`, with no extra control or tuning. The model runner handles compilation in this case, and not our custom decorator. The backend is `eager`.
- **`2` (`DYNAMO_ONCE`)**: Uses `TorchDynamo` with a custom dispatcher; the model is compiled once, and we then reuse the compiled code. This should avoid repeated guard checks and recompilation, and will likely have better perf than `1`.
- **`3` (`INDUCTOR`)**: Uses `TorchInductor` backend with some custom …
> `torch.compile`: integrate aphrodite with torch.compile

- aphrodite/attention/backends/pallas.py
- aphrodite/worker/tpu_model_runner.py
Split the batch dimension into sub-batches and invoke the paged attention kernel for each sub-batch, rather than invoking the kernel only once for the entire batch
> TPU: fix SMEM OOM error

- aphrodite/endpoints/openai/logits_processors.py
tokenizer.vocab_size returns the size of the vocab excluding added tokens while len(tokenizer) returns the proper size of the vocab including the added tokens. As seen here: https://github.com/huggingface/transformers/blob/79254c9b61ac2e1a6e0f698c38b1654159095e2e/src/transformers/tokenization_utils_fast.py#L234-L239 https://github.com/huggingface/transformers/blob/79254c9b61ac2e1a6e0f698c38b1654159095e2e/src/transformers/tokenization_utils_fast.py#L275-L279
This prevents errors when using added tokens as logit bias, such as trying to bias eos_token_id on for example meta-llama/Llama-3.1-8B-Instruct
I am unsure if there are any other places where this should be changed, but looking at the use cases of vocab_size in the rest of the repo, they mostly seem to be derived from the model config, …
> fix: use proper vocab size for logit_bias

- docs/src/content/docs/installation/installation-rocm.md
The command two lines above has the missing parameter -t to apply a tag, this line does not.
This PR adds the missing parameter.
> docs: fix missing parameter in rocm installation guide

- aphrodite/endpoints/openai/api_server.py
- aphrodite/endpoints/openai/protocol.py
- aphrodite/endpoints/openai/serving_tokenization.py
Input format:
```sh
curl -s -X POST \
-H "Content-Type: application/json" \
-d '{
"model": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
"inputs": [
"What is a man?",
"A miserable little pile of secrets"
]
}' http://localhost:2242/v1/batch/tokenize
```
Response format:
```json
{
"results": [
{
"tokens": [
128000,
3923,
374,
264,
893,
30
],
"count": 6
},
{
"tokens": [
128000,
32,
50739,
2697,
27402,
315,
24511
],
"count": 7
}
]
}
```
Benchmarked with 1000 requests, with a total of 102588 randomly generated characters, at a batch size of 100:
```
Single Tokenization:
Total time: 2.3760s
Requests: 1000 (successful: 1000)
Average request time: 1281.11ms
Throughput: 420.87 requests/sec
Token throughput: 28992.62 tokens/sec
Batch Tokenization:
Total time: 0.0526s
Batches: 10 of size 100 …
```
> API: add batched tokenizer endpoint

- aphrodite/platforms/cuda.py
Works with prefix caching and chunked prefill. Tested on A100:
Need flashinfer first:
```sh
pip install -U flashinfer-python
```
FI uses JIT compilation for its CUDA kernels, so the first request will take a few minutes to complete.
```sh
APHRODITE_ATTENTION_BACKEND="FLASHINFER" aphrodite run Qwen/Qwen3-0.6B \
--kv-cache-dtype fp8
```
> [V1] feat: support fp8 kv on ampere through flashinfer

- aphrodite/common/sampling_params.py
- aphrodite/endpoints/openai/protocol.py
- aphrodite/v1/engine/logprobs.py
- aphrodite/v1/engine/output_processor.py
This PR implements [DeepConf (Deep Think with Confidence)](https://arxiv.org/abs/2508.15260), a confidence-based early stopping mechanism that automatically halts text generation when the model's confidence drops below a threshold.
To test via the API (logprobs is needed):
```sh
curl -s -X POST http://localhost:2242/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model": "NousResearch/Meta-Llama-3.1-8B-Instruct",
"prompt": "Let me think about this carefully... um... what is the square root of 144? I need to... let me see... I'\''m not sure about this... maybe it'\''s...",
"enable_deepconf": true,
"logprobs": 0,
"deepconf_window_size": 50,
"deepconf_threshold": 10
}' | jq .
```
Output:
<details>
<summary>Click to expand</summary>
```json
{
"id": …
```
> feat: add DeepConf sampling

- CMakeLists.txt
- aphrodite/common/envs.py
- setup.py
Flash Attention kernels are very expensive to build, and they are rebuilt every time you make a small change to other unrelated kernels. This PR lets you skip that step by exporting the `APHRODITE_DISABLE_FLASH_ATTN=1` env var.
> build: add option to disable flash attn compilation

- aphrodite/attention/ops/prefix_prefill.py
> fix: cast offsets tensor `bn` to `tl.int64` to avoid GPU segfault

- kernels/layernorm_kernels.cu
- kernels/layernorm_quant_kernels.cu
So far, RMSNorm is done. No decrease in accuracy:
Before:
```
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|-----|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.6808|±  |0.0128|
|     |       |strict-match    |     5|exact_match|↑  |0.6740|±  |0.0129|
```
After:
```
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|-----|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.6816|±  |0.0128|
|     |       |strict-match    |     5|exact_match|↑  |0.6748|±  |0.0129|
```
Performance (Olmoe-1B-7B):
> [kernel] feat: vectorized kernels

- requirements/cuda.txt
Fixes #1535 
Looks like xformers regularly deletes their pre-releases, so we should just set the version to anything above `0.0.32.post2` to support pytorch 2.8 + cuda 12.8.
> [build] fix: relax xformers dependency version
