aphrodite/modeling/layers/attention.py

This PR adds support for ALiBi bias for PagedAttention. Not immediately useful, but good for future-proofing.

feat: add alibi bias attention

---

aphrodite/common/config.py
aphrodite/modeling/layers/attention.py
aphrodite/modeling/models/llama.py
aphrodite/processing/scheduler.py
kernels/pos_encoding_kernels.cu
requirements.txt

Draft PR. Manages to load the model (unlike before), but the output is nonsense and the throughput is very slow (1 tokens/s compared to the projected ~130). Needs fixing before merge.

feat: Group-Query Attention for Llama-2 70B

---

aphrodite/modeling/hf_downloader.py
aphrodite/modeling/models/llama.py

Add safetensor model support for faster loading. Not ready yet.

add safetensor support

---

aphrodite/common/logits_processor.py
aphrodite/common/sampling_params.py
aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/protocol.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/args_tools.py
aphrodite/modeling/layers/sampler.py

Solves #18 
Adding logit processor back for now, and will hopefully maintain it this time.

fix: openai server

---

aphrodite/modeling/layers/sampler.py

Dumb but critical mistake, I forgot to set keepdim=True which breaks TFS with multiple generations in flight

chore:fix tfs

---

aphrodite/modeling/models/llama.py

Recent change stopped pulling the arguments from the model config

Restore RoPE Scaling

---

aphrodite/endpoints/api_server_kobold.py
aphrodite/endpoints/protocol.py

KobldAI endpoint with minimum functionality based on `openai/api_server.py` and [tgi-kai-bridge](https://github.com/g4rg/tgi-kai-bridge)
```
curl -X 'GET' 'http://127.0.0.1:8000/api/v1/model'
curl -X 'POST' 'http://127.0.0.1:8000/api/v1/generate' \
-H 'Content-Type: application/json' \
-d '{
"max_context_length": 512,
"max_length": 80,
"prompt": "Niko the kobold stalked carefully down the alley, his small scaly figure obscured by a dusky cloak that fluttered lightly in the cold winter breeze."
}'
```

KoboldAI endpoint

---

pyproject.toml
requirements.txt

Thanks to @ycros for the fix. 
Closes #40

fix: torch version mismatch

---

aphrodite/endpoints/api_server_kobold.py
aphrodite/endpoints/klite.embd

Adds a copy of embedded Kobold Lite Web UI that automatically starts with the Kobold API Server.
Kobold Lite updates may be found at https://github.com/LostRuins/lite.koboldai.net 
Simply change the localflag at the top to true, and replace the klite.embd file

Adds a copy of embedded Kobold Lite Web UI

---

kernels/attention/attention_kernels.cu

This PR properly sets the maximum dynamic shared memory size for the attention kernels.

fix: attention kernel attribute

---

aphrodite/common/sampling_params.py
aphrodite/endpoints/api_server_kobold.py
aphrodite/endpoints/protocol.py
aphrodite/modeling/layers/sampler.py

Tested and working on kobold(use_default_badwords) and ooba(custom_token_bans) endpoints on single GPU. Pending testing on multi GPU but I see no reason why it would break.

feat:Enable banning tokens

---

docker/Dockerfile

Correct Conda Env Creation in Dockerfile

---

aphrodite/modeling/layers/sampler.py
aphrodite/modeling/metadata.py
aphrodite/task_handler/worker.py

Pre-allocate tensors used to prune hidden states to potentially fix the CPU sync delay in samplers.

fix: sync CPU delay in sampler

---

aphrodite/common/utils.py

Memory limits imposed by containers (using cgroups) are not considered by `psutil.virtual_memory().total`.
Tested on Docker with cgroups v1 (Ubuntu 20.04) and v2 (Arch)

fix: cpu memory limit detection for containers

---

aphrodite/endpoints/openai/api_server.py

This PR adds API Keys for the OpenAI endpoint server. 
Example:
```sh
python -m aphrodite.endpoints.openai.api_server --model PygmalionAI/pygmalion-2-7b --api-keys EMPTY EMPTY1
```

chore: api keys for OAI server

---

aphrodite/common/logits_processor.py
aphrodite/common/sampling_params.py
aphrodite/endpoints/openai/api_server.py

Reworked from:
https://github.com/PygmalionAI/aphrodite-engine/issues/18
https://github.com/PygmalionAI/aphrodite-engine/pull/19

Add logit_bias support for OpenAI API endpoint

---

aphrodite/modeling/loader.py
aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/phi1_5.py
requirements.txt

This PR adds support for [Phi 1.5](https://huggingface.co/microsoft/phi-1_5).

feat: phi 1.5 support

---

aphrodite/common/config.py
aphrodite/modeling/hf_downloader.py
aphrodite/modeling/loader.py

Read the quantization method from the quantization config if available.

chore: quant config

---

aphrodite/common/config.py
aphrodite/modeling/hf_downloader.py
aphrodite/modeling/layers/activation.py
aphrodite/modeling/layers/quantization/awq.py
aphrodite/modeling/layers/quantization/base_config.py
aphrodite/modeling/models/gpt_j.py
aphrodite/modeling/models/gpt_neox.py
aphrodite/modeling/models/phi1_5.py

This PR adds an scaled activation function to enable AWQ support for all models.

feat: awq for all models

---

aphrodite/modeling/layers/layernorm.py
aphrodite/modeling/models/llama.py
aphrodite/modeling/models/mistral.py
kernels/layernorm.cpp
kernels/layernorm_kernels.cu

Fused add RMSNorm kernel for llama and mistral models. Should speed up generation speed by 5-10%.

feat: fused add RMSNorm kernels

---

aphrodite/endpoints/kobold/api_server.py
aphrodite/endpoints/kobold/klite.embd
aphrodite/endpoints/kobold/protocol.py

* update KoboldAI lite embedded UI to v97
* update behaviour to reflect koboldcpp - best effort (#42)

chore: KoboldAI/koboldcpp updates

---

README.md
aphrodite/common/config.py
aphrodite/endpoints/ooba/api_server.py

Reverts the problematic commit.

Revert "fix: correct auto ntk scaling_factor for 4k ctx case"

---

aphrodite/modeling/loader.py
aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/mixtral.py

Lazily import the model class modules so we avoid importing models we're not using.

chore: implement lazy module loader for models

---

aphrodite/common/logits_processor.py
aphrodite/common/sequence.py
aphrodite/modeling/layers/sampler_mirostat.py
aphrodite/modeling/sampling_metadata.py
aphrodite/processing/scheduler.py
aphrodite/task_handler/model_runner.py

chore: fix Python 3.8+ compatibility

---

aphrodite/common/config.py
aphrodite/modeling/hf_downloader.py
aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/mixtral.py

This PR will switch to Mixtral's HuggingFace implementation to support safetensors and parallelism with experts across GPUs. Note that until HF adds support for Mixtral .pt weights, we cannot load them.

feat: mixtral HF with expert parallelism

---

aphrodite/common/config.py
aphrodite/endpoints/openai/api_server.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/async_aphrodite.py
aphrodite/modeling/models/gpt_neox.py
aphrodite/modeling/models/mixtral.py
aphrodite/processing/block_manager.py
aphrodite/processing/scheduler.py
kernels/activation_kernels.cu
kernels/attention/attention_kernels.cu
kernels/cache_kernels.cu
kernels/layernorm_kernels.cu
kernels/pos_encoding_kernels.cu
kernels/quantization/gptq/matrix_view.cuh
kernels/quantization/gptq/q_gemm.cu
kernels/quantization/squeezellm/quant_cuda_kernel.cu

I had a bunch of fixes and other stuff accumulating in my local repo so I'm dumping all of them here. The changes are:
- Fix quantized mixtral for multi-gpu
- Disable ray's usage stats collection
- Fix an error in the scheduler by allowing the recovery of the remaining sequence in a sequence group using the re-computation mechanism.
- Do not return ignored sequences twice
- Support attention bias for NeoX (ref. [huggingface/transformers/#28126](https://github.com/huggingface/transformers/pull/28126))
- Allow execution on non-zero GPU IDs by adding device guards
- Support CUDA graph for GPTQ and SqueezeLLM

chore: backlog 1

---

aphrodite/modeling/layers/rejection.py
tests/samplers/test_rejection_sampling.py

This PR adds Rejection Sampling from the paper [Accelerating Large Language Model Decoding with Speculative Sampling](https://arxiv.org/pdf/2302.01318.pdf).

feat: rejection sampler

---

.github/workflows/publish.yml
.github/workflows/scripts/cuda-install.sh
build-linux-wheel.sh
environment.yaml
pyproject.toml
requirements.txt
setup.py

This PR bumps the CUDA version to 12.1 and PyTorch to 2.1.2

feat: bump cuda to 12.1

---

aphrodite/modeling/sampling_metadata.py

Looks like we were setting temperature to 1 all the time, hopefully this fixes it.

fix temperature being set to 1 in all cases

---

aphrodite/modeling/sampling_metadata.py

fix: logprobs for dynatemp

---

aphrodite/common/config.py
aphrodite/common/test_utils.py
aphrodite/endpoints/llm.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/args_tools.py
aphrodite/modeling/megatron/communication_op.py
aphrodite/modeling/megatron/custom_all_reduce.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/worker.py
kernels/all_reduce/custom_all_reduce.cu
kernels/all_reduce/custom_all_reduce.cuh
kernels/all_reduce/custom_all_reduce_test.cu
kernels/ops.h
kernels/pybind.cpp
requirements.txt
setup.py
tests/benchmarks/throughput.py

Custom all-reduce kernels for parallelism, similar to [TensorRT-LLM's](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/cpp/tensorrt_llm/kernels/customAllReduceKernels.cu) allreduce kernels. 
A continuation of #184

feat: add custom allreduce kernels

---

environment.yaml
requirements.txt

Highly annoying issue, came down to updating both torch and xformers.

fix: bump torch to 2.2.0

---

.github/workflows/publish.yml
aphrodite/modeling/layers/quantization/gguf.py
build-linux-wheel.sh
kernels/quantization/marlin/marlin_cuda_kernel.cu
kernels/quantization/quip/origin_order.cu
setup.py

feat: backport kernels

---

aphrodite/modeling/layers/sampler.py

Probably unnecessary to have a mask here.

fix: remove the mask for quadratic sampling

---

aphrodite/common/logits_processor.py
aphrodite/common/sampling_params.py
aphrodite/modeling/layers/sampler.py

Also corrected type hints for existing logit processors, and stop_token_ids while I was at it.

Fix logit processor declarations and application

---

aphrodite/modeling/layers/sampler.py

As title says. Bonus: typo fix in comment, reduced code in _sample loops.

Fix zero token output due to temperature bias.

---

aphrodite/modeling/layers/quantization/gptq.py

#235 introduced some issues related to Marlin that'd make GPTQ models output garbage. This PR fixes that. A future PR will restore Marlin support.

fix: garbage output from GPTQ

---

aphrodite/common/config.py
aphrodite/common/utils.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/args_tools.py
aphrodite/modeling/layers/activation.py
aphrodite/modeling/layers/attention.py
aphrodite/modeling/layers/linear.py
aphrodite/modeling/layers/quantization/awq.py
aphrodite/modeling/layers/quantization/gptq.py
aphrodite/modeling/layers/quantization/squeezellm.py
aphrodite/modeling/layers/rotary_embedding.py
aphrodite/modeling/layers/vocab_parallel_embedding.py
aphrodite/modeling/loader.py
aphrodite/task_handler/cache_engine.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/worker.py

In case we want to add other devices in the future, like CPU, XPU, etc, would be useful to not have hard-coded "cuda" device.

feat: allow further support for non-cuda devices

---

examples/gguf_to_torch.py

Greatly reduced peak ram usage when loading gguf models.

Add sharding and safetensors support to converting gguf.

---

aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/opt.py

This PR adds support for facebook's [Open Pretrained Transformer](https://huggingface.co/facebook/opt-2.7b) (OPT) class of models.

feat: OPT model support

---

aphrodite/modeling/layers/triton_kernel/fused_moe.py
aphrodite/modeling/models/deepseek.py
aphrodite/modeling/models/mixtral.py
kernels/moe/moe_ops.cpp
kernels/moe/moe_ops.h
kernels/moe/softmax.cu
setup.py

feat: fused top-k kernels for MoE

---

aphrodite/engine/aphrodite_engine.py
aphrodite/modeling/megatron/communication_op.py
aphrodite/modeling/megatron/cupy_utils.py
aphrodite/modeling/megatron/custom_all_reduce.py
aphrodite/modeling/megatron/parallel_state.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/worker.py
requirements.txt

Switching back to CuPy cuda graphs, following vLLM's implementation.

fix: memory leaks due to nccl cuda graphs

---

aphrodite/lora/models.py
aphrodite/lora/worker_manager.py
aphrodite/modeling/loader.py
aphrodite/task_handler/model_runner.py

Since we already moved the mappings to individual models, we should make changes to the lora worker to reflect that.

fix: LoRA support for mixtral

---

aphrodite/common/logits_processor.py

logit bias is a simple additive bias.
also, biases are floats, not longs.

fix logit bias logitproc

---

aphrodite/common/config.py
aphrodite/lora/layers.py

Title. Doesn't work with GGUF yet, only tested with GPTQ. Tested for correctness as well, no issues.

fix: lora on quantized models (barred gguf)

---

setup.py

Fix typo in marlin kernel path.

---

aphrodite/endpoints/kobold/klite.embd
aphrodite/endpoints/openai/api_server.py

"you can make a PR, just copy paste the embed file from kcpp" alpin says

Replace klite.embd with current version

---

kernels/quantization/bitsandbytes/format.cu
kernels/quantization/bitsandbytes/gemm_s4_f16.cu
kernels/quantization/bitsandbytes/int4_fp16_gemm_kernels.cu

Just a few checks here and there. Compiles for sm_75 now.

fix: backport bnb kernels

---

aphrodite/common/config.py
aphrodite/modeling/layers/quantization/bitsandbytes.py
kernels/quantization/bitsandbytes/format.cu
kernels/quantization/bitsandbytes/gemm_s4_f16.cu
kernels/quantization/bitsandbytes/int4_fp16_gemm_kernels.cu

PITA. Seems like the 8bit stuff works, but not 4bit. Let's restrict it.

fix: bnb on Turing GPUs

---

aphrodite/common/config.py
aphrodite/common/logger.py
aphrodite/common/utils.py
aphrodite/endpoints/kobold/api_server.py
aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/serving_chat.py
aphrodite/endpoints/openai/serving_completions.py
aphrodite/endpoints/openai/serving_engine.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/async_aphrodite.py
aphrodite/engine/metrics.py
aphrodite/engine/ray_tools.py
aphrodite/modeling/hf_downloader.py
aphrodite/modeling/layers/linear.py
aphrodite/modeling/loader.py
aphrodite/modeling/megatron/custom_all_reduce.py
aphrodite/modeling/models/__init__.py
aphrodite/processing/scheduler.py
aphrodite/task_handler/cache_engine.py
aphrodite/task_handler/model_runner.py
aphrodite/transformers_utils/tokenizer.py
requirements.txt

Using a better logging system, and added memory usage log for the model weights.

chore: logging refactor

---

aphrodite/modeling/layers/vocab_parallel_embedding.py

The exl2 PR #305 broke TP for some quants. This here fixes it.

fix: tensor parallel with GPTQ and AWQ quants

---

README.md

readme: add tabby, fix docker, add colab

---

aphrodite/modeling/layers/quantization/aqlm.py

Should massively speed up dequantization.

fix: optimize aqlm dequantization

---

aphrodite/endpoints/openai/serving_engine.py

resolves #328 
Normalize negative logprobs so they do not exceed -1000.

fix: logprobs when inf or nan

---

CMakeLists.txt
MANIFEST.in
build-linux-wheel.sh
cmake/hipify.py
cmake/utils.cmake
environment.yaml
pyproject.toml
requirements-rocm.txt
requirements.txt
setup.py

Ref. [Daniel Pfiefer's 2017 Talk](https://www.youtube.com/watch?v=bsXLMQ6WgIk) and [vllm#2830](https://github.com/vllm-project/vllm/pull/2830/)
This PR switches to a cmake build system. Much cleaner, and shortens build times.

feat: CMake Build System Generator

---

docker/.env
docker/Dockerfile
docker/docker-compose.yml
docker/entrypoint.sh

@AlpinDale: With [Pull Request #327](https://github.com/PygmalionAI/aphrodite-engine/pull/327) you made some changes to "allow docker port and host to be changed", but that was already the case and these changes broke it because of how Docker works internally. So here's a fix for that to make the Docker stuff work again, and my explanations of what's changed (and why):
- The HOST must always be 0.0.0.0 since that's for listening on all interfaces *inside* the container, there's no other sensible option, as 127.0.0.1 would restrict it to localhost *inside* the container (preventing access from outside of Docker, and even from the host), and no other hostname/address would exist *inside* the container (since we don't have any other networks within the aphrodite-engine service). That's why I …

docker-fixes

---

aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/llama.py

fix: restore backwards compatibility with old Yi models

---

aphrodite/modeling/layers/sampler.py

Shockingly moist `samplers.py` is now slightly DRYer.

Hoist sampler internals into a single function.

---

aphrodite/__init__.py
aphrodite/common/config.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/async_aphrodite.py
aphrodite/engine/ray_tools.py
aphrodite/executor/executor_base.py
aphrodite/executor/gpu_executor.py
aphrodite/executor/ray_gpu_executor.py

To keep in line with upstream, model execution has been split into modular classes now. Should make support for other devices, e.g. CPU, much easier. Also, engine code is simplified now.

feat: model execution refactor

---

aphrodite/modeling/layers/activation.py
kernels/activation_kernels.cu
kernels/ops.h
kernels/pybind.cpp
setup.py

Also install the correct cupy version for cuda 11.

feat: add approximate gelu activation kernels

---

aphrodite/common/config.py
aphrodite/modeling/megatron/communication_op.py
setup.py

Windows support for later in a follow-up PR, along with CPU.

fix: explicitly disallow installation on non-linux platforms

---

aphrodite/common/config.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/args_tools.py
aphrodite/executor/utils.py
aphrodite/transformers_utils/tokenizer.py
aphrodite/transformers_utils/tokenizer_group/__init__.py
aphrodite/transformers_utils/tokenizer_group/base_tokenizer_group.py
aphrodite/transformers_utils/tokenizer_group/ray_tokenizer_group.py
aphrodite/transformers_utils/tokenizer_group/tokenizer_group.py

This PR separates the tokenization into a different process, to prevent blocking the event loop when tokenizing incoming requests.

feat: async tokenization

---

aphrodite/processing/block_manager.py
aphrodite/processing/evictor.py

Mostly for when context shift is *disabled*.

fix: optimize context shift performance

---

CMakeLists.txt
cmake/hipify.py
cmake/utils.cmake
environment.yaml
pyproject.toml
requirements.txt
setup.py
update-runtime.sh

Take 3. Still stuck with the micromamba issue.

CMake build system

---

aphrodite/modeling/layers/sampler.py

Exactly what it says on the tin

Missed .items() and assert

---

kernels/layernorm_kernels.cu
kernels/reduction.cuh

Should reduce latency in the layernorm by a fair bit.

feat: optimized layernorm kernels

---

aphrodite/common/config.py
aphrodite/engine/args_tools.py
aphrodite/modeling/layers/logits_processor.py
aphrodite/modeling/layers/quantization/bitsandbytes.py
aphrodite/modeling/layers/sampler.py
aphrodite/modeling/models/cohere.py
aphrodite/processing/block/block_table.py
aphrodite/processing/block_manager_v1.py
aphrodite/processing/block_manager_v2.py
aphrodite/processing/interfaces.py
aphrodite/processing/scheduler.py

The dummy arg `num_lookahead_slots` has been added.

Speculative Decoding Part 4: Lookahead scheduling

---

aphrodite/modeling/models/cohere.py

Based on https://github.com/vllm-project/vllm/pull/3985 https://github.com/vllm-project/vllm/pull/3919
Fix weight loading for exl2.

Improve cohere model.

---

aphrodite/common/config.py
aphrodite/engine/args_tools.py
aphrodite/modeling/layers/quantization/__init__.py
aphrodite/modeling/layers/quantization/eetq.py

Very simple implementation, doesn't work with TP.
Example model here: https://huggingface.co/alpindale/Mistral-7B-Instruct-v0.2-EETQ

feat: EETQ

---

examples/gguf_to_torch.py

Allow setting config-path when converting ggufs.

Allow setting config-path when converting ggufs.

---

aphrodite/endpoints/cli.py
aphrodite/modeling/hf_downloader.py
aphrodite/modeling/layers/linear.py
aphrodite/modeling/loader.py

Reduce vram usage during exl2 model loading.

Split the exl2 weight ASAP.

---

aphrodite/common/logger.py
aphrodite/modeling/hf_downloader.py
aphrodite/transformers_utils/config.py
aphrodite/transformers_utils/tokenizer.py
examples/gguf_to_torch.py

Support sharded `.gguf` files in a directory. Also the user can supply the `config.json` and tokenizer in the directory.

Support sharded ggufs.

---

aphrodite/endpoints/kobold/klite.embd
aphrodite/endpoints/openai/api_server.py

Updates the kobold lite embed and version number in the api.

Update Kobold Lite Embed

---

aphrodite/endpoints/openai/api_server.py

fix: OPTIONS requests in the API

---

aphrodite/common/logits_processor.py

also swapped function order to be consistent.
Init, then Serial, then Batched.

Fix non-batched implementation of logit bias

---

aphrodite/common/sequence.py
aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/protocol.py
aphrodite/endpoints/openai/serving_chat.py
aphrodite/engine/aphrodite_engine.py
aphrodite/modeling/layers/logits_processor.py
aphrodite/modeling/loader.py
aphrodite/modeling/models/baichuan.py
aphrodite/modeling/models/bloom.py
aphrodite/modeling/models/chatglm.py
aphrodite/modeling/models/dbrx.py
aphrodite/modeling/models/deepseek.py
aphrodite/modeling/models/falcon.py
aphrodite/modeling/models/gemma.py
aphrodite/modeling/models/gpt2.py
aphrodite/modeling/models/gpt_bigcode.py
aphrodite/modeling/models/gpt_j.py
aphrodite/modeling/models/gpt_neox.py
aphrodite/modeling/models/internlm2.py
aphrodite/modeling/models/llama.py
aphrodite/modeling/models/llava.py
aphrodite/modeling/models/mixtral.py
aphrodite/modeling/models/mpt.py
aphrodite/modeling/models/olmo.py
aphrodite/modeling/models/opt.py
aphrodite/modeling/models/phi.py
aphrodite/modeling/models/qwen.py
aphrodite/modeling/models/stablelm.py
aphrodite/processing/scheduler.py

A collection of various fixes, I made each fix a separate commit, revert the ones you don't want.

Tiny fixes

---

aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/serving_engine.py
aphrodite/engine/aphrodite_engine.py

As discussed here: https://github.com/PygmalionAI/aphrodite-engine/issues/318#issuecomment-2088895545

Fixed REVISION variable not being passed on.

---

aphrodite/modeling/guided_decoding/outlines_logits_processors.py
requirements-common.txt

https://github.com/vllm-project/vllm/pull/4189
Bump lmfe version to 0.9.8 to fix various issues.

Fix minor bugs in outlines and lmfe.

---

CMakeLists.txt
aphrodite/lora/layers.py
aphrodite/lora/lora.py
aphrodite/lora/models.py
aphrodite/lora/punica.py
aphrodite/lora/utils.py
aphrodite/lora/worker_manager.py
kernels/punica/bgmv/bgmv_bf16_bf16_fp16.cu
kernels/punica/bgmv/bgmv_bf16_fp16_bf16.cu
kernels/punica/bgmv/bgmv_bf16_fp16_fp16.cu
kernels/punica/bgmv/bgmv_bf16_fp32_fp16.cu
kernels/punica/bgmv/bgmv_config.h
kernels/punica/bgmv/bgmv_fp16_bf16_bf16.cu
kernels/punica/bgmv/bgmv_fp16_bf16_fp16.cu
kernels/punica/bgmv/bgmv_fp16_fp16_bf16.cu
kernels/punica/bgmv/bgmv_fp16_fp32_bf16.cu
kernels/punica/bgmv/bgmv_fp32_bf16_fp16.cu
kernels/punica/bgmv/bgmv_fp32_fp16_bf16.cu
kernels/punica/bgmv/bgmv_fp32_fp32_bf16.cu
kernels/punica/bgmv/bgmv_fp32_fp32_fp16.cu
kernels/punica/bgmv/generator.py
kernels/punica/punica_ops.cc

fix: lora errors

---

setup.py

So #345 can finally be closed :3

Fix quants installation on ROCM

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
docker/Dockerfile

chore: add contribution guidelines + Code of Conduct

---

aphrodite/endpoints/openai/protocol.py
aphrodite/endpoints/openai/serving_chat.py

This is the re-targeted [PR502](https://github.com/PygmalionAI/aphrodite-engine/pull/502) 🤗

feat: list support in message.content

---

aphrodite/modeling/guided_decoding/outlines_logits_processors.py

There's no aphrodite.py in outlines repo

---

aphrodite/common/sequence.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/async_aphrodite.py
aphrodite/engine/output_processor/interfaces.py
aphrodite/engine/output_processor/multi_step.py
aphrodite/engine/output_processor/single_step.py
aphrodite/engine/output_processor/util.py
aphrodite/modeling/layers/logits_processor.py
aphrodite/modeling/layers/sampler.py
aphrodite/modeling/sampling_metadata.py
aphrodite/processing/scheduler.py
aphrodite/task_handler/cpu_model_runner.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/neuron_model_runner.py

This PR allows us to request prompt logprobs when doing chunked prefill. For the sake of simplicity, we're also removing mirostat sampling. It's too difficult to maintain; if there's demand for it, I may bring it back.

feat: prompt logprobs with chunked prefill

---

aphrodite/common/sampling_params.py
aphrodite/modeling/layers/sampler.py
aphrodite/modeling/sampling_metadata.py

A fix for the phenomenon noted in #544 
Dynatemp is currently removed, but I'll implement it again later.

fix: sampler indexing issues in distributed environments

---

CMakeLists.txt
aphrodite/common/config.py
aphrodite/quantization/__init__.py
aphrodite/quantization/gptq_marlin.py
kernels/quantization/gptq_marlin/gptq_marlin.cu
kernels/quantization/gptq_marlin/gptq_marlin.cuh
kernels/quantization/gptq_marlin/gptq_marlin_repack.cu
kernels/quantization/quant_ops.cpp
kernels/quantization/quant_ops.h
tests/benchmarks/throughput.py

This PR adds the Neural Magic marlin kernels for GPTQ inference. Should automatically serialize compatible GPTQ models to Marlin, resulting in massive high-bsz throughput improvements.

feat: marlin kernels for GPTQ

---

aphrodite/attention/backends/abstract.py
aphrodite/attention/backends/flashinfer.py
aphrodite/attention/selector.py
aphrodite/common/config.py
aphrodite/common/sequence.py
aphrodite/common/utils.py
aphrodite/task_handler/model_runner.py
kernels/cache.h
kernels/cache_kernels.cu
kernels/pybind.cpp

`input_prompts=500, num_gpus=2, gpu="NVIDIA A40", nvlink=True model=Meta-Llama-3-8B`
**FlashAttention-2**:
`Throughput: 8.60 requests/s, Input tokens/s: 1733.22, Output tokens/s: 1792.37`
**Xformers**:
`Throughput: 8.45 requests/s, Input tokens/s: 1702.24, Output tokens/s: 1760.33`
**FlashInfer**:
`Throughput: 7.79 requests/s, Input tokens/s: 1568.72, Output tokens/s: 1622.26`

feat: FlashInfer backend for decoding phase

---

aphrodite/endpoints/openai/api_server.py
aphrodite/engine/args_tools.py
requirements-common.txt

Used as an optional event loop replacement
[Website](https://github.com/MagicStack/uvloop)

Add uvloop

---

aphrodite/modeling/layers/fused_moe/__init__.py
aphrodite/modeling/layers/fused_moe/fused_moe.py
aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/arctic.py
aphrodite/quantization/__init__.py
aphrodite/quantization/deepspeedfp.py
aphrodite/transformers_utils/configs/arctic.py

https://huggingface.co/Snowflake/snowflake-arctic-instruct

model: Arctic Snowflake

---

aphrodite/endpoints/openai/serving_chat.py

ummmm u cant index a python dict w/ dot notation, sillyhead

Fix OpenAI chat completions compatibility

---

CMakeLists.txt
aphrodite/_custom_ops.py
aphrodite/common/config.py
aphrodite/common/sequence.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/async_aphrodite.py
aphrodite/modeling/layers/mamba/ops/causal_conv1d.py
aphrodite/modeling/layers/mamba/ops/mamba_ssm.py
aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/jamba.py
aphrodite/processing/scheduler.py
aphrodite/spec_decode/draft_model_runner.py
aphrodite/task_handler/cache_engine.py
aphrodite/task_handler/cpu_model_runner.py
aphrodite/task_handler/embedding_model_runner.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/model_runner_base.py
aphrodite/task_handler/neuron_model_runner.py
aphrodite/task_handler/worker_base.py
aphrodite/task_handler/xpu_model_runner.py
kernels/mamba/causal_conv1d/causal_conv1d.cu
kernels/mamba/causal_conv1d/causal_conv1d.h
kernels/mamba/causal_conv1d/static_switch.h
kernels/mamba/mamba_ssm/selective_scan.h
kernels/mamba/mamba_ssm/selective_scan_fwd.cu
kernels/mamba/mamba_ssm/static_switch.h
kernels/ops.h
kernels/torch_bindings.cpp
requirements-cuda.txt

Adds support for the mamba infrastructure. This PR only adds Jamba, since it's easier to support due to having attention layers. Other PRs will add Mamba and RWKV.

Mamba infrastrucuture support

---

aphrodite/common/utils.py
aphrodite/endpoints/cli.py
aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/args.py
aphrodite/endpoints/openai/protocol.py
aphrodite/endpoints/openai/run_batch.py
aphrodite/endpoints/openai/serving_chat.py
aphrodite/endpoints/openai/serving_completions.py
aphrodite/endpoints/openai/serving_embedding.py
aphrodite/endpoints/openai/serving_engine.py
aphrodite/engine/args_tools.py
examples/openai_api/batched_example.jsonl
examples/openai_api/batched_inference.md
examples/openai_api/chat_completion.py
examples/openai_api/completion.py
examples/openai_api/embedding.py
examples/openai_api/vision.py
requirements-common.txt

Heavy refactoring of the API, and adding multiple new features that have been on hold since forever:
- Function Calling
- Batched API Endpoint
- GPT4-Vision API
- Adding Chat & Completions to the `aphrodite` binary
Also added examples for all API types, along with documentation for batched endpoint.
TODO:

OpenAI API Refactor

---

aphrodite/common/config.py
aphrodite/distributed/parallel_state.py
aphrodite/modeling/layers/linear.py
aphrodite/modeling/layers/vocab_parallel_embedding.py
aphrodite/modeling/models/llama.py
aphrodite/spec_decode/draft_model_runner.py
aphrodite/task_handler/cache_engine.py
aphrodite/task_handler/embedding_model_runner.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/worker.py

To run models with tensor parallel sizes where their number of attention heads is not divisible by the GPU count.

feat: Asymmetric Tensor Parallel

---

aphrodite/modeling/layers/linear.py

Very ugly fix by isolating all asymmetric TP changes in the linear layers using if-else statements. Let's try and narrow it down to the exact place where the issue occurs. Traceback:
2xA40, model: https://huggingface.co/hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4
```console
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/austin/disk1/aphrodite-engine/conda/envs/aphrodite-runtime/bin/aphrodite", line 8, in <module>
[rank0]:     sys.exit(main())
[rank0]:              ^^^^^^
[rank0]:   File "/home/austin/disk1/aphrodite-engine/aphrodite/endpoints/cli.py", line 148, in main
[rank0]:     args.dispatch_function(args)
[rank0]:   File "/home/austin/disk1/aphrodite-engine/aphrodite/endpoints/cli.py", line 28, in serve
[rank0]:     run_server(args)
[rank0]:   File …
```

fix: asymmetric TP changes breaking the gptq and awq quants with TP

---

aphrodite/engine/args_tools.py
aphrodite/modeling/guided_decoding/outlines_logits_processors.py

chore: sort args

---

CMakeLists.txt
aphrodite/_custom_ops.py
aphrodite/quantization/__init__.py
aphrodite/quantization/qqq.py
aphrodite/quantization/utils/marlin_utils_test_qqq.py
aphrodite/quantization/utils/quant_utils.py
kernels/quantization/marlin/dense/common/base.cuh
kernels/quantization/marlin/dense/common/mem.cuh
kernels/quantization/marlin/qqq/marlin_qqq_gemm_kernel.cu
kernels/quantization/quant_ops.h
kernels/torch_bindings.cpp
update-runtime.sh

Paper: https://arxiv.org/abs/2406.09904
Repo: https://github.com/HandH1998/QQQ

feat: support for QQQ W4A8 quantization

---

.github/workflows/publish.yml
CMakeLists.txt
aphrodite/attention/backends/flash_attn.py
aphrodite/attention/backends/flashinfer.py
aphrodite/attention/selector.py
aphrodite/spec_decode/draft_model_runner.py
docker/Dockerfile
environment.yaml
requirements-cuda.txt
setup.py
update-runtime.sh

vllm-flash-attn doesn't compile for 12.4 which may introduce complications

bump to torch 2.4.0 and cuda to 12.4, add aphrodite_flash_attn

---

aphrodite/attention/__init__.py
aphrodite/attention/layer.py
aphrodite/attention/selector.py
aphrodite/common/config.py
aphrodite/common/outputs.py
aphrodite/common/sequence.py
aphrodite/common/utils.py
aphrodite/endpoints/llm.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/args_tools.py
aphrodite/inputs/__init__.py
aphrodite/inputs/data.py
aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/bart.py
aphrodite/processing/block/utils.py
aphrodite/processing/scheduler.py
aphrodite/task_handler/enc_dec_model_runner.py
aphrodite/task_handler/utils.py
aphrodite/task_handler/worker.py
docs/.vitepress/config.mts
docs/pages/usage/encoder-decoder.md
docs/pages/usage/models.md
examples/offline_inference/encoder_decoder_inference.py

Seems to work extremely well. 1xA40, bart-large-cnn:

feat: initial encoder-decoder support with BART model

---

aphrodite/modeling/layers/sampler.py

Infs lead to NaNs in the logits which make samplers very sad.

quadratic sampling: separate diff from logits to filter out NaNs.

---

aphrodite/common/utils.py
aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/rpc/client.py
aphrodite/endpoints/openai/rpc/server.py

To resolve some of the "Address already in use" issues

fix: move zeromq rpc frontend to IPC instead of TCP

---

aphrodite/quantization/awq_marlin.py
aphrodite/quantization/gptq_marlin.py
aphrodite/quantization/utils/marlin_utils.py

Some min_capability issues on T4 GPUs

fix: GPTQ/AWQ on Colab

---

aphrodite/attention/backends/flashinfer.py

Seems like it was outputting garbage

fix: flashinfer outputs

---

aphrodite/common/sequence.py
aphrodite/processing/block_manager_v1.py

fix: minor adjustments to scheduler and block manager

---

aphrodite/lora/layers.py
aphrodite/modeling/layers/sampler.py
aphrodite/spec_decode/medusa_worker.py
aphrodite/spec_decode/multi_step_worker.py
aphrodite/spec_decode/proposer_worker_base.py
aphrodite/spec_decode/smaller_tp_proposer_worker.py
aphrodite/spec_decode/spec_decode_worker.py

chore: decouple `should_modify_greedy_probs_inplace`

---

aphrodite/modeling/models/jamba.py
aphrodite/task_handler/model_runner.py

Remove the redundant CG Mamba buffer and save memory

chore: mamba cache single buffer

---

aphrodite/attention/backends/placeholder_attn.py
aphrodite/attention/layer.py
aphrodite/attention/selector.py
aphrodite/common/config.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/args_tools.py
aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/interfaces.py
aphrodite/modeling/models/mamba.py
aphrodite/modeling/models/mamba_cache.py
aphrodite/processing/interfaces.py
aphrodite/processing/placeholder_block_space_manager.py
aphrodite/processing/scheduler.py
aphrodite/task_handler/cache_engine.py
aphrodite/task_handler/cpu_model_runner.py
aphrodite/task_handler/cpu_worker.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/openvino_model_runner.py
aphrodite/task_handler/openvino_worker.py
aphrodite/task_handler/tpu_model_runner.py
aphrodite/task_handler/worker.py
aphrodite/task_handler/xpu_model_runner.py

Thanks to Neural Magic's efforts.

feat: mamba model support

---

aphrodite/common/config.py
aphrodite/common/utils.py
aphrodite/engine/args_tools.py
aphrodite/executor/cpu_executor.py
aphrodite/executor/openvino_executor.py
aphrodite/task_handler/tpu_worker.py

Like swap_space and cpu_offload_gib

fix: allow passing float for GiB arguments

---

aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/serving_engine.py

feat: add lora loading/unloading api endpoint

---

aphrodite/endpoints/chat_utils.py
aphrodite/modeling/model_loader/loader.py
aphrodite/modeling/models/blip2.py
aphrodite/modeling/models/chameleon.py
aphrodite/modeling/models/fuyu.py
aphrodite/modeling/models/interfaces.py
aphrodite/modeling/models/internvl.py
aphrodite/modeling/models/llava.py
aphrodite/modeling/models/llava_next.py
aphrodite/modeling/models/minicpmv.py
aphrodite/modeling/models/paligemma.py
aphrodite/modeling/models/phi3v.py
aphrodite/modeling/models/utils.py
aphrodite/multimodal/audio.py
aphrodite/multimodal/base.py
aphrodite/multimodal/registry.py
aphrodite/multimodal/utils.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/xpu_model_runner.py
docs/pages/developer/multimodal.md
requirements-common.txt

This PR adds support for audio modality, similar to vision modality, and renames all vision methods to multimodal methods. Currently does not implement an audio model, only builds the pipeline.

feat: support for Audio modality

---

aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/solar.py

Just an upscaled Phi-3. 
https://huggingface.co/upstage/solar-pro-preview-instruct

feat: add Solar model support

---

aphrodite/engine/aphrodite_engine.py
aphrodite/modeling/models/__init__.py
aphrodite/plugins/__init__.py
aphrodite/task_handler/worker_base.py
requirements-common.txt

This PR adds a plugin system to Aphrodite, allowing users to register out-of-tree models and worker methods easily, among other things. Documentation will follow soon.

feat: add aphrodite plugin system

---

aphrodite/quantization/compressed_tensors/compressed_tensors.py
aphrodite/quantization/compressed_tensors/schemes/compressed_tensors_w8a16_fp8.py
aphrodite/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
aphrodite/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_int8.py
aphrodite/quantization/compressed_tensors/utils.py
requirements-common.txt
requirements-test.txt

This reverts commit f5bbf07c9043cc381071174ecb6941dbd1c2a4f0.

Revert "chore: use the `compressed-tensors` library to avoid code reuse (#704)"

---

aphrodite/distributed/device_communicators/tpu_communicator.py

Changes global rank and world size into local rank and local world size.

feat: add support for multi-host TPU

---

aphrodite/distributed/device_communicators/tpu_communicator.py

Since Ray is an optional dependency...

fix: import ray under a guard

---

aphrodite/common/sampling_params.py
aphrodite/modeling/layers/sampler.py

fix: empty sampler output when temperature is too low

---

aphrodite/modeling/model_loader/weight_utils.py

To fix issues with loading some FP8 models with quantized KV

fix: weight loading for scalars

---

aphrodite/version.py

ci: bump to 0.6.1.post1

---

aphrodite/common/config.py
aphrodite/modeling/layers/fused_moe/fused_moe.py
aphrodite/modeling/layers/fused_moe/layer.py
aphrodite/modeling/models/jamba.py
aphrodite/quantization/__init__.py
aphrodite/quantization/experts_int8.py
aphrodite/quantization/fp8.py

To load MoE models in INT8, for Ampere GPUs.

feat: add experts_int8 support

---

aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/exaone.py

* feat: add support for ExaoneForCausalLM models
* progress bar

feat: add Exaone model support

---

aphrodite/common/sampling_params.py
aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/protocol.py
aphrodite/modeling/layers/sampler.py
aphrodite/modeling/sampling_metadata.py

#650 again, with a do_temperatures implementation and API support

feat: bring back dynatemp

---

requirements-common.txt

Resolves #753 
Ref: vllm-project/vllm#1047

fix: add pandas to requirements

---

aphrodite/modeling/sampling_metadata.py

Includes typehint corrections and the discussed changes to prompt logprob sampler values.

Simplify construction of sampling_metadata

---

aphrodite/common/config.py
aphrodite/engine/args_tools.py
aphrodite/modeling/model_loader/loader.py
aphrodite/modeling/model_loader/weight_utils.py
aphrodite/modeling/models/llama.py
aphrodite/transformers_utils/config.py

```sh
aphrodite run mistralai/Ministral-8B-Instruct-2410 --load-format mistral --tokenizer-mode mistral --config-format mistral
```

feat: ministral support

---

install_windows.ps1

fix: windows wheel url

---

aphrodite/_custom_ops.py
aphrodite/modeling/layers/linear.py
aphrodite/modeling/parameter.py
aphrodite/quantization/__init__.py
aphrodite/quantization/hqq_marlin.py
aphrodite/quantization/utils/marlin_utils.py
formatting.ps1
kernels/quantization/gptq_marlin/gptq_marlin.cu
kernels/quantization/gptq_marlin/marlin_dtypes.cuh
kernels/quantization/quant_ops.h
kernels/torch_bindings.cpp

Adapted from vllm-project/vllm#9766

feat: add HQQ quantization support

---

kernels/torch_bindings.cpp
pyproject.toml

fix: compilation of gptq_marlin_gemm object

---

aphrodite/version.py
install_windows.ps1

To apply the critical fix from #800

ci: bump to 0.6.3.post1

---

aphrodite/endpoints/openai/api_server.py

The Kobold API is now enabled by default. Authentication is handled the same way as OpenAI API, through both `x-api-key` and `Authorization: Bearer`. 
You can also disable the Kobold Lite UI by passing the `SERVE_KOBOLD_LITE_UI=0` environment variable.
Also some logging for important routes, and a fix for badwordsids.

frontend: enable kobold api by default

---

aphrodite/engine/args_tools.py

fix: --max-seq-len-to-capture arg

---

aphrodite/endpoints/llm.py

feat: add chat method for LLM class

---

aphrodite/common/config.py
aphrodite/processing/scheduler.py
aphrodite/task_handler/model_runner.py

feat: support chunked prefill with LoRA

---

aphrodite/common/sequence.py
aphrodite/engine/args_tools.py
aphrodite/engine/async_aphrodite.py
aphrodite/executor/gpu_executor.py
aphrodite/executor/ray_gpu_executor.py
aphrodite/task_handler/model_runner_base.py
aphrodite/task_handler/multi_step_model_runner.py
aphrodite/task_handler/multi_step_worker.py
aphrodite/task_handler/worker.py
aphrodite/task_handler/worker_base.py
tests/benchmarks/engine/throughput.py
tests/multi_step/test_correctness.py
tests/worker/test_model_input.py

Based on the design proposed in vllm-project/vllm#7000
Follow-up to #713

feat: multi-step scheduling

---

aphrodite/common/sampling_params.py
aphrodite/endpoints/openai/protocol.py
aphrodite/modeling/layers/sampler.py
aphrodite/modeling/sampling_metadata.py

A direct port of https://github.com/oobabooga/text-generation-webui/pull/5677/files
Key changes:
- Add DRY parameters to OpenAI models
- Add DRY parameters to SamplingParams
- Add DRY tensors to SamplingTensors
- Implement _apply_dry() logits processor

feat: Add DRY (Do not Repeat Yourself) sampling

---

aphrodite/common/sampling_params.py
aphrodite/endpoints/openai/protocol.py
aphrodite/modeling/layers/sampler.py
aphrodite/modeling/sampling_metadata.py
tests/samplers/test_sampler.py

See here: https://huggingface.co/docs/transformers/internal/generation_utils#transformers.NoRepeatNGramLogitsProcessor
Not very useful, added as a warmup for more serious samplers coming soon.

feat: add no_repeat_ngram sampler

---

aphrodite/modeling/layers/sampler.py

DRY would crash when run concurrently.

sampler: fix DRY concurrency issue

---

aphrodite/modeling/layers/sampler.py

Reference: oobabooga/text-generation-webui#6047
Needs manual testing, but the test units pass.

sampler: optimize DRY performance using z-algorithm

---

aphrodite/common/sampling_params.py
aphrodite/endpoints/openai/protocol.py

Integer ID only may be cumbersome.

sampler: allow parsing sampler order using strings

---

aphrodite/lora/punica.py

Triton is kinda unstable on XPU.

xpu: disable punica kernels for XPU

---

aphrodite/modeling/layers/linear.py
aphrodite/modeling/model_loader/weight_utils.py
aphrodite/modeling/models/internlm2.py
tests/models/test_internvl.py

feat: AWQ quantization for InternVL

---

aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/rpc/__init__.py
aphrodite/endpoints/openai/rpc/client.py
aphrodite/endpoints/openai/rpc/server.py
aphrodite/engine/async_aphrodite.py
aphrodite/engine/protocol.py
aphrodite/server/launch.py
tests/benchmarks/engine/backend_request_func.py

See vllm-project/vllm#7394 for a more detailed write-up
Under very high loads, ZeroMQ can drop messages, due to their [watermarking](https://zeromq.org/socket-api/#high-water-mark) system.

api: fix crashes under very high loads

---

kernels/attention/attention_utils.cuh

rocm: fix compile issues with rocm 6.2

---

aphrodite/common/config.py
aphrodite/common/sequence.py
aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/eagle.py
aphrodite/modeling/models/medusa.py
aphrodite/spec_decode/draft_model_runner.py
aphrodite/spec_decode/multi_step_worker.py
aphrodite/spec_decode/spec_decode_worker.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/multi_step_worker.py
aphrodite/task_handler/worker.py
aphrodite/task_handler/worker_base.py
aphrodite/transformers_utils/config.py
aphrodite/transformers_utils/configs/__init__.py
aphrodite/transformers_utils/configs/eagle.py
pytest.ini
tests/benchmarks/engine/throughput.py
tests/spec_decode/e2e/test_eagle_correctness.py
tests/spec_decode/e2e/test_medusa_correctness.py
tests/spec_decode/test_multi_step_worker.py

Reference: vllm-project/vllm#6830

spec decode: add support for EAGLE

---

aphrodite/modeling/layers/linear.py
aphrodite/quantization/marlin.py

quantization: update marlin to use `AphroditeParameters`

---

aphrodite/engine/aphrodite_engine.py
aphrodite/engine/async_aphrodite.py
tests/multi_step/test_correctness_async_llm.py
tests/multi_step/test_correctness_llm.py

core: add multi-step scheduling support for the synchronous engine

---

aphrodite/distributed/device_communicators/custom_all_reduce_utils.py

distributed: fix custom allreduce p2p cache file generation

---

aphrodite/engine/args_tools.py
aphrodite/executor/neuron_executor.py
aphrodite/task_handler/neuron_worker.py

neuron: add support for tensor parallelism

---

aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/rpc/__init__.py
aphrodite/endpoints/openai/rpc/client.py
aphrodite/endpoints/openai/rpc/server.py
requirements-common.txt

Unloading:
```sh
$ curl -s -X DELETE http://localhost:2242/v1/model/unload | jq .
{
"status": "success",
"message": "Model unloaded successfully"
}
```
Loading:
```sh
$ curl -X POST http://localhost:2242/v1/model/load \
-H "Content-Type: multipart/form-data" \
-F "config_file=@config.yaml"; echo
{"status":"success","message":"Model loaded successfully"}
```

api: add endpoint for loading and unloading the model

---

aphrodite/common/envs.py
aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/args.py

If you pass a different model name in your request, it'll unload current model and attempt to load that one.
TODO:

api: add inline model loading

---

CMakeLists.txt
aphrodite/_custom_ops.py
aphrodite/executor/ray_utils.py
aphrodite/lora/models.py
aphrodite/modeling/layers/fused_moe/__init__.py
aphrodite/modeling/layers/fused_moe/fused_moe.py
aphrodite/modeling/layers/fused_moe/layer.py
aphrodite/modeling/model_loader/utils.py
aphrodite/modeling/models/jamba.py
aphrodite/modeling/models/na_vit.py
aphrodite/multimodal/image.py
aphrodite/multimodal/utils.py
aphrodite/platforms/cuda.py
aphrodite/quantization/compressed_tensors/compressed_tensors.py
aphrodite/quantization/compressed_tensors/compressed_tensors_moe.py
aphrodite/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
aphrodite/quantization/fp8.py
aphrodite/transformers_utils/config.py
kernels/moe/marlin_moe_ops.cu
kernels/moe/marlin_moe_ops.h
kernels/moe/torch_bindings.cpp

feat: add fused Marlin MoE kernel

---

aphrodite/modeling/models/clip.py
aphrodite/modeling/models/llava_next.py
aphrodite/modeling/models/paligemma.py
aphrodite/modeling/models/siglip.py
aphrodite/multimodal/utils.py
examples/vision/vision_example.py
tests/conftest.py
tests/models/test_llava_next.py
tests/multimodal/test_utils.py

chore: multi-image support for llava-next

---

aphrodite/common/sequence.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/async_aphrodite.py
aphrodite/processing/scheduler.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/worker_base.py

core: add virtual engine for async outproc

---

aphrodite/_custom_ops.py
aphrodite/common/config.py
aphrodite/common/envs.py
aphrodite/quantization/awq_triton.py
tests/kernels/test_awq_triton.py

quants: add triton kernels for AWQ

---

aphrodite/common/sequence.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/async_aphrodite.py
aphrodite/engine/output_processor/multi_step.py
aphrodite/task_handler/model_runner.py
aphrodite/task_handler/multi_step_model_runner.py
aphrodite/task_handler/multi_step_worker.py

2xA6000, Llama 3.1 8B, ShareGPT dataset:
Main:
```
============ Serving Benchmark Result ============
Successful requests:                     1000
Benchmark duration (s):                  156.27
Total input tokens:                      229971
Total generated tokens:                  199533
Request throughput (req/s):              6.40
Input token throughput (tok/s):          1471.67
Output token throughput (tok/s):         1276.88
---------------Time to First Token----------------
Mean TTFT (ms):                          56639.04
Median TTFT (ms):                        52991.59
P99 TTFT (ms):                           115273.94
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          218.04
Median TPOT (ms):                        158.79
P99 TPOT (ms): …
```

core: improve async postproc + multi-step performance

---

aphrodite/common/config.py
aphrodite/engine/args_tools.py
aphrodite/modeling/model_loader/neuron.py
aphrodite/quantization/__init__.py
aphrodite/quantization/neuron_quant.py
aphrodite/worker/neuron_model_runner.py
examples/offline_inference/neuron_int8_quantization.py

neuron: add 8bit quantization for Neuron

---

aphrodite/quantization/awq_triton.py

quants: improve awq_triton throughput

---

Dockerfile.cpu
aphrodite/common/config.py
aphrodite/executor/cpu_executor.py
aphrodite/modeling/model_loader/loader.py
aphrodite/platforms/__init__.py
aphrodite/platforms/cpu.py
aphrodite/platforms/interface.py
aphrodite/platforms/tpu.py
aphrodite/quantization/compressed_tensors/compressed_tensors.py
aphrodite/worker/cpu_worker.py
cmake/cpu_extension.cmake
kernels/cpu/cpu_types_x86.hpp
kernels/cpu/dnnl_helper.hpp
kernels/cpu/quant.cpp
kernels/cpu/torch_bindings.cpp
kernels/cpu/utils.cpp

cpu: add support for W8A8 quantization via compressed-tensor

---

aphrodite/modeling/layers/fused_moe/fused_moe.py

To make it work with quantized models too.

fix: grouped_topk return type

---

CMakeLists.txt
aphrodite/_custom_ops.py
aphrodite/attention/backends/rocm_flash_attn.py
kernels/rocm/attention.cu
kernels/rocm/ops.h
kernels/rocm/torch_bindings.cpp
setup.py
tests/kernels/test_attention.py

rocm: add custom paged attention kernels for ROCm

---

aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/minicpm.py
aphrodite/modeling/models/minicpm3.py

model: add support for MiniCPM-3

---

aphrodite/common/config.py
aphrodite/executor/ray_tpu_executor.py
aphrodite/executor/tpu_executor.py
aphrodite/worker/multi_step_tpu_worker.py
aphrodite/worker/tpu_model_runner.py

tpu: implement multi-step scheduling

---

aphrodite/_custom_ops.py
aphrodite/quantization/qqq.py
aphrodite/quantization/utils/w8a8_utils.py
kernels/cpu/quant.cpp
kernels/cpu/torch_bindings.cpp
kernels/quantization/compressed_tensors/int8_quant_kernels.cu
kernels/quantization/quant_ops.h
kernels/torch_bindings.cpp
tests/kernels/test_int8_quant.py

kernel: asymmetric AQ AZP quantization kernels

---

kernels/ops.h

build: fix compilation for causal_conv1d_fwd kernel signature

---

aphrodite/_custom_ops.py
aphrodite/attention/backends/rocm_flash_attn.py
kernels/rocm/attention.cu
kernels/rocm/ops.h
kernels/rocm/torch_bindings.cpp
tests/kernels/test_attention.py

rocm: add support for FP8 KV cache in the custom paged attention kernels

---

aphrodite/common/utils.py
aphrodite/worker/model_runner.py
aphrodite/worker/xpu_model_runner.py

XPU uses this class too, and other devices may use it in the future.

misc: rename `CudaMemoryProfiler` to `DeviceMemoryProfiler`

---

kernels/all_reduce/custom_all_reduce.cuh
kernels/all_reduce/custom_all_reduce_test.cu

Should also improve perf by 6-7us

fix: unsafe all-reduce sync

---

aphrodite/quantization/utils/layer_utils.py

Caused by Machete kernel integration.

fix: torch.compile dynamo fix

---

aphrodite/common/sequence.py
aphrodite/engine/output_processor/multi_step.py
aphrodite/modeling/layers/rejection_sampler.py
aphrodite/modeling/layers/sampler.py
aphrodite/spec_decode/batch_expansion.py
aphrodite/spec_decode/spec_decode_worker.py
aphrodite/spec_decode/util.py
aphrodite/transformers_utils/detokenizer.py
tests/conftest.py
tests/spec_decode/e2e/conftest.py
tests/spec_decode/e2e/test_eagle_correctness.py
tests/spec_decode/e2e/test_logprobs.py
tests/spec_decode/e2e/test_medusa_correctness.py
tests/spec_decode/e2e/test_mlp_correctness.py
tests/spec_decode/e2e/test_ngram_correctness.py

Also fixed the spec decode e2e tests.

chore: support prompt_logprobs with speculative decoding

---

aphrodite/common/config.py
aphrodite/common/sequence.py
aphrodite/endpoints/llm.py
aphrodite/engine/aphrodite_engine.py
aphrodite/processing/scheduler.py
tests/benchmarks/engine/prioritization.py

Only adding core support for now, integration later.

feat: add Priority-based Scheduling

---

aphrodite/endpoints/openai/args.py
aphrodite/endpoints/openai/serving_chat.py
aphrodite/endpoints/openai/tool_parsers/__init__.py
aphrodite/endpoints/openai/tool_parsers/llama_tool_parser.py
examples/chat_templates/llama_3.1_json_tool.jinja
examples/chat_templates/llama_3.2_json_tool.jinja
tests/tool_use/test_chat_completions.py
tests/tool_use/test_parallel_tool_calls.py
tests/tool_use/utils.py

Append this to your launch command:
```sh
--chat-template examples/chat_templates/llama_{3.1,3.2}_json_tool.jinja --enable-auto-tool-choice --tool-call-parser {llama3_json}
```

API: add tool calling support for Llama 3.1 and 3.2

---

Dockerfile
aphrodite/attention/backends/blocksparse_attn.py
aphrodite/attention/backends/flash_attn.py
aphrodite/attention/backends/flashinfer.py
aphrodite/attention/backends/ipex_attn.py
aphrodite/attention/backends/pallas.py
aphrodite/attention/backends/rocm_flash_attn.py
aphrodite/attention/backends/torch_sdpa.py
aphrodite/attention/backends/xformers.py
aphrodite/worker/embedding_model_runner.py
aphrodite/worker/enc_dec_model_runner.py
aphrodite/worker/model_runner.py
aphrodite/worker/tpu_model_runner.py
aphrodite/worker/tpu_worker.py
aphrodite/worker/xpu_model_runner.py
tests/kernels/test_encoder_decoder_attn.py

Also updated Flashinfer to 0.1.6 in the Dockerfile.

torch.compile: use empty tensor instead of None for profiling

---

aphrodite/attention/backends/flash_attn.py
aphrodite/attention/backends/flashinfer.py
aphrodite/common/config.py
aphrodite/common/sequence.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/args_tools.py
aphrodite/engine/async_aphrodite.py
aphrodite/engine/output_processor/multi_step.py
aphrodite/processing/block/block_table.py
aphrodite/processing/block_manager_v1.py
aphrodite/processing/block_manager_v2.py
aphrodite/processing/interfaces.py
aphrodite/processing/placeholder_block_space_manager.py
aphrodite/processing/scheduler.py
aphrodite/worker/multi_step_model_runner.py
aphrodite/worker/multi_step_worker.py
kernels/prepare_inputs/advance_step.cu

A few caveats:
- `n` larger than 1 not supported
- logit bias not supported
- num batched tokens is restricted to max_model_len

core: add support for chunked prefill + multi-step scheduling

---

aphrodite/common/envs.py
aphrodite/distributed/device_communicators/custom_all_reduce.py

`export APHRODITE_FORCE_P2P=1`

distributed: add env var to force custom all-reduce by skipping p2p check

---

aphrodite/modeling/layers/pooler.py
aphrodite/modeling/models/__init__.py
aphrodite/modeling/models/qwen2_rm.py

On 2xA6000:
```sh
aphrodite run Qwen/Qwen2.5-Math-RM-72B -tp 2 --cpu-offload-gb 100
```
Still runs decently fast with the majority of weights offloaded to CPU.
Usage:
```py
from transformers import AutoModel, AutoTokenizer
from openai import OpenAI
model_name = "Qwen/Qwen2.5-Math-RM-72B"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
chat = [
{"role": "system", "content": "Please reason step by step, and put your final answer within \\boxed{}."},
{"role": "user", "content": "Janet’s ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells the remainder at the farmers' market daily for $2 per fresh duck egg. How much in dollars does she make every day at the farmers' market?"}, …
```

model: add support for Qwen2.5-Math-RM-72B reward model

---

Dockerfile.openvino
aphrodite/_custom_ops.py
aphrodite/attention/backends/openvino.py
aphrodite/common/envs.py
aphrodite/executor/openvino_executor.py
aphrodite/modeling/model_loader/openvino.py
aphrodite/triton_utils/importing.py
aphrodite/worker/openvino_model_runner.py
aphrodite/worker/openvino_worker.py
requirements-openvino.txt

8bit KV produces garbage at the moment.

OpenVINO: add support for GPU, fix Docker build

---

aphrodite/common/config.py
aphrodite/engine/aphrodite_engine.py

More fields are added if they differ from the default values.

logging: only log the non-default parameters in engine

---

aphrodite/attention/backends/flash_attn.py
aphrodite/attention/backends/flashinfer.py
aphrodite/forward_context.py
aphrodite/spec_decode/draft_model_runner.py
aphrodite/worker/embedding_model_runner.py
aphrodite/worker/enc_dec_model_runner.py
aphrodite/worker/model_runner.py
tests/kernels/test_flash_attn.py
tests/kernels/test_flashinfer.py

Follow-up PR will fully integrate torch.compile.

[`torch.compile`]: add forward context for attention

---

aphrodite/attention/backends/flashinfer.py

Might as well get this one in too before we move on.

[`torch.compile`]: add forward context for flashinfer

---

aphrodite/modeling/models/opt.py

Fixes https://huggingface.co/cjvt/OPT_GaMS-1B

fix: OPT model loading for checkpoints with no tied embeds

---

aphrodite/common/config.py
aphrodite/common/sampling_params.py
aphrodite/endpoints/openai/protocol.py
aphrodite/engine/aphrodite_engine.py
aphrodite/engine/args_tools.py
aphrodite/engine/async_aphrodite.py
aphrodite/engine/multiprocessing/client.py
aphrodite/modeling/guided_decoding/__init__.py
aphrodite/modeling/guided_decoding/outlines_decoding.py
aphrodite/modeling/guided_decoding/outlines_logits_processors.py
aphrodite/modeling/guided_decoding/utils.py
aphrodite/modeling/guided_decoding/xgrammar_decoding.py
aphrodite/platforms/__init__.py
aphrodite/platforms/interface.py
requirements-common.txt
tests/endpoints/llm/test_guided_generate.py
tests/modeling/test_guided_processors.py

Re-doing #1193 to fix the #1194 issue.

feat: add support for xgrammar + GBNF grammars

---

CMakeLists.txt
aphrodite/_custom_ops.py
aphrodite/quantization/__init__.py
aphrodite/quantization/vptq.py
kernels/quantization/quant_ops.h
kernels/quantization/vptq/gemm_kernels.cu
kernels/torch_bindings.cpp

Based on vllm-project/vllm#12117
Fix #1152
Tested with https://huggingface.co/VPTQ-community/Meta-Llama-3.1-8B-Instruct-v12-k65536-4096-woft. The 405B variants do not work.
TODO:

quantization: add VPTQ support

---

CMakeLists.txt
aphrodite/_custom_ops.py
aphrodite/modeling/layers/fused_moe/fused_marlin_moe.py
aphrodite/modeling/model_loader/utils.py
aphrodite/quantization/awq_marlin.py
aphrodite/quantization/compressed_tensors/compressed_tensors_moe.py
aphrodite/quantization/gptq_marlin.py
aphrodite/quantization/utils/marlin_utils.py
kernels/moe/marlin_kernels/marlin_moe_kernel.h
kernels/moe/marlin_kernels/marlin_moe_kernel_ku4.cu
kernels/moe/marlin_kernels/marlin_moe_kernel_ku4.h
kernels/moe/marlin_kernels/marlin_moe_kernel_ku4b8.cu
kernels/moe/marlin_kernels/marlin_moe_kernel_ku8b128.cu
kernels/moe/marlin_kernels/marlin_moe_kernel_ku8b128.h
kernels/moe/marlin_moe_ops.cu
kernels/moe/torch_bindings.cpp
kernels/quantization/gptq_marlin/gptq_marlin.cu
kernels/quantization/vptq/gemm_kernels.cu

8x22B AWQ, 2xA6000, no nvlink/p2p
Old: 15.2 tok/s
New: 44.8 tok/s

MoE: add FusedMoE support for gptq_marlin and awq_marlin

---

aphrodite/transformers_utils/config.py
tests/models/decoder_only/vision_language/test_internvl.py

To avoid modifying HF behaviour.

fix: deprecate registration of custom configs to HF

---

aphrodite/engine/args_tools.py
aphrodite/processing/block/block_table.py
aphrodite/processing/block_manager_v2.py

fix: block manager v2 with encoder-decoder models

---

aphrodite/modeling/layers/linear.py
aphrodite/modeling/model_loader/loader.py
aphrodite/modeling/model_loader/weight_utils.py
aphrodite/modeling/models/llama.py
aphrodite/quantization/gguf.py
aphrodite/transformers_utils/config.py

The initial config loading for Llama models should be over 2x faster. Tokenizer could use a similar improvement but needs more work. Does not bring throughput improvements.

quantization: optimize GGUF config loading and refactor parameter packing and forwarding

---

aphrodite/lora/models.py
aphrodite/modeling/models/qwen.py

LoRA: add support for Qwen models

---

aphrodite/engine/args_tools.py
aphrodite/modeling/models/llama.py
aphrodite/modeling/models/registry.py

Also fixed a bug where sampler wasn't properly assigned when using Pipeline Parallel with llama.

chore: improve model support check in registry

---

aphrodite/quantization/vptq.py

Thanks @AlpinDale  for supporting VPTQ in aphrodite-engine.
As the bug discussed in this PR #1199,  I reproduced the issue fixed that in this PR.
Most previous models in vptq-community didn't fuse the perm into codebooks. So, user might need to fuse it in local if they want to run it in parallel (TP>1).
```
pip install vptq && python -m vptq.tools.pre_process \
--input_path xx --output_path xx
```
FYI @BlairSadewitz @YangWang92
Thanks

[BUG FIX] fix bugs to load llama 405B by vptq quant method

---

aphrodite/engine/multiprocessing/engine.py

fix: propagate priority through multiprocessing engine

---

aphrodite/_custom_ops.py
aphrodite/modeling/layers/activation.py
aphrodite/modeling/models/minicpm.py
kernels/activation_kernels.cu
kernels/ops.h
kernels/torch_bindings.cpp

Ref: https://proceedings.mlr.press/v119/kurtz20a/kurtz20a.pdf

kernel: add support for FATReLU activation

---

aphrodite/spec_decode/ngram_worker.py

Perform lookup on CPU and only trigger the CPU<->GPU comms when there's a match.

spec decoding: slightly optimize ngram lookup performance

---

aphrodite/profiler/__init__.py
aphrodite/profiler/layerwise_profile.py
aphrodite/profiler/utils.py
aphrodite/worker/model_runner.py
examples/offline_profile.py
tools/profiler/print_layerwise_table.py
tools/profiler/visualize_layerwise_profile.py

chore: add CUDA layerwise profiler

---

aphrodite/attention/backends/abstract.py
aphrodite/attention/backends/xformers.py
aphrodite/modeling/layers/pooler.py
aphrodite/modeling/models/bert.py
aphrodite/modeling/models/registry.py
examples/offline_inference/embedding_inference.py
tests/conftest.py
tests/models/embedding/language/test_embedding.py
tests/models/embedding/utils.py

Based on vllm-project/vllm#9056

model: add support for the BERT family of models

---

aphrodite/common/utils.py
aphrodite/executor/gpu_executor.py
aphrodite/worker/model_runner.py
aphrodite/worker/worker.py

core: better memory usage profiling logs

---

aphrodite/modeling/layers/activation.py
aphrodite/modeling/models/llava.py
aphrodite/modeling/models/pixtral.py
aphrodite/modeling/models/qwen2_vl.py
aphrodite/transformers_utils/processor.py
examples/vision/vision_example.py

Previously, it was the mistral model format only.
vllm-project/vllm#9036

model: add support for HF transformers format of Pixtral

---

aphrodite/attention/backends/flashinfer.py
aphrodite/common/envs.py

`export APHRODITE_FLASHINFER_FORCE_TENSOR_CORES=1`

chore: add env variable to force tensor cores in flashinfer

---

aphrodite/endpoints/chat_utils.py
aphrodite/modeling/models/utils.py
kernels/cpu/quant.cpp

```json
[
{
"role": "user",
"content": [
"What's in this image?",
{
"image_url": "http://foo.bar/n.png"
}
]
}
]
```

api: simple image input format

---

aphrodite/common/config.py

Breaking changes had to be fixed.

fix: speculative decoding with the new task changes

---

aphrodite/attention/backends/flash_attn.py
aphrodite/attention/layer.py
aphrodite/attention/selector.py
aphrodite/common/config.py
aphrodite/worker/cache_engine.py
aphrodite/worker/cpu_model_runner.py
aphrodite/worker/cpu_worker.py
aphrodite/worker/model_runner.py
aphrodite/worker/openvino_model_runner.py
aphrodite/worker/openvino_worker.py
aphrodite/worker/tpu_model_runner.py
aphrodite/worker/xpu_model_runner.py

feat: support sliding window in flash attention

---

tests/benchmarks/engine/backend_request_func.py
tests/benchmarks/engine/serving.py

feat: goodput metrics support

---

aphrodite/modeling/models/mamba.py
aphrodite/modeling/models/registry.py

Tested with [tiiuae/Falcon3-Mamba-7B-Instruct](https://huggingface.co/tiiuae/Falcon3-Mamba-7B-Instruct)

models: add support for `FalconMamba` models

---

aphrodite/attention/backends/xformers.py
aphrodite/attention/selector.py
aphrodite/common/envs.py
aphrodite/endpoints/llm.py
aphrodite/engine/multiprocessing/engine.py
aphrodite/inputs/registry.py
aphrodite/modeling/layers/logits_processor.py
aphrodite/modeling/models/interfaces_base.py
aphrodite/modeling/models/minicpmv.py
aphrodite/modeling/models/paligemma.py
aphrodite/modeling/models/qwen2_vl.py
aphrodite/transformers_utils/detokenizer.py
aphrodite/transformers_utils/detokenizer_utils.py
aphrodite/v1/attention/backends/flash_attn.py
aphrodite/v1/core/kv_cache_manager.py
aphrodite/v1/core/scheduler.py
aphrodite/v1/engine/aphrodite_engine.py
aphrodite/v1/executor/gpu_executor.py
aphrodite/v1/outputs.py
aphrodite/v1/request.py
aphrodite/v1/sample/metadata.py
aphrodite/v1/sample/sampler.py
aphrodite/v1/tokenizer/detokenizer.py
aphrodite/v1/worker/gpu_model_runner.py
aphrodite/v1/worker/gpu_worker.py

Based on the vLLM v1 design. Not yet ready for prod use. A lot of features still missing.

feat: Aphrodite Engine v1

---

aphrodite/modeling/models/intern_vit.py
aphrodite/modeling/models/internlm2_ve.py
aphrodite/modeling/models/internvl.py
aphrodite/modeling/models/registry.py
examples/vision/vision_example.py

Tested with [OpenGVLab/Mono-InternVL-2B-S1-3](https://huggingface.co/OpenGVLab/Mono-InternVL-2B-S1-3)

models: add support for Mono-InternVL models

---

aphrodite/common/utils.py
aphrodite/worker/model_runner.py
kernels/ops.h
kernels/torch_bindings.cpp

Also some nice progress bars for it.

core: improve cuda graph memory usage with tensor weakref

---

aphrodite/modeling/layers/fused_moe/__init__.py
aphrodite/modeling/layers/fused_moe/fused_marlin_moe.py
aphrodite/modeling/layers/fused_moe/fused_moe.py
aphrodite/modeling/layers/fused_moe/layer.py
aphrodite/modeling/models/granitemoe.py
aphrodite/quantization/awq_marlin.py
aphrodite/quantization/compressed_tensors/compressed_tensors_moe.py
aphrodite/quantization/gptq_marlin.py

PowerMoE, fp16, RTX 4090
torch.compile level 0: 239.4 tok/s
torch.compile level 1: 239.5 tok/s
torch.compile level 2: 239.8 tok/s
torch.compile level 3: 250.9 tok/s
torch.compile level 4: 247.1 tok/s

feat: torch.compile support for MoE models

---

aphrodite/common/envs.py
aphrodite/modeling/layers/fused_moe/layer.py
aphrodite/quantization/__init__.py
aphrodite/quantization/mxfp4.py
aphrodite/quantization/utils/mxfp4_utils.py

feat: MXFP4 quantization via FlashInfer

---

aphrodite/modeling/layers/mamba/mamba_mixer.py
aphrodite/modeling/layers/mamba/mamba_mixer2.py
aphrodite/modeling/layers/mamba/mamba_utils.py
aphrodite/modeling/models/bamba.py
aphrodite/modeling/models/falcon_h1.py
aphrodite/modeling/models/granitemoehybrid.py
aphrodite/modeling/models/jamba.py
aphrodite/modeling/models/mamba.py
aphrodite/modeling/models/mamba2.py
aphrodite/modeling/models/nemotron_h.py
aphrodite/modeling/models/zamba2.py
aphrodite/v1/attention/backends/mamba1_attn.py
aphrodite/v1/attention/backends/mamba_selectors.py
kernels/mamba/mamba_ssm/selective_scan.h
kernels/mamba/mamba_ssm/selective_scan_fwd.cu

V1 feat: add Mamba1 support

---

aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/args.py
aphrodite/endpoints/openai/serving_responses.py
aphrodite/endpoints/tool_server.py

feat: demo tool server

---

aphrodite/common/sampling_params.py
aphrodite/endpoints/openai/protocol.py
aphrodite/utils/__init__.py
aphrodite/v1/core/sched/output.py
aphrodite/v1/core/sched/scheduler.py
aphrodite/v1/request.py
aphrodite/v1/worker/gpu_input_batch.py
aphrodite/v1/worker/gpu_model_runner.py

Replaces #1402, see that PR's description for details on how this works.

[V1] feat: add support for banned strings

---

aphrodite/quantization/fp8.py

Needed better detection for `modules_to_not_convert`

fix: Qwen3Moe FP8

---

aphrodite/v1/worker/gpu_model_runner.py
aphrodite/v1/worker/gpu_worker.py
aphrodite/v1/worker/lora_model_runner_mixin.py

With `max_loras=32`
Main:
```
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:02:16
```
PR:
```
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:11
```
143 seconds -> 11 seconds

chore: faster LoRA startup

---

aphrodite/endpoints/openai/serving_engine.py
aphrodite/inputs/data.py
aphrodite/inputs/preprocess.py
aphrodite/multimodal/__init__.py
aphrodite/multimodal/hasher.py
aphrodite/multimodal/inputs.py
aphrodite/multimodal/processing.py
aphrodite/v1/engine/processor.py
tests/v1/engine/test_processor_multi_modal_uuids.py

feat: allow passing `multi_modal_uuids` as multimodal identifiers

---

aphrodite/distributed/kv_events.py
aphrodite/distributed/kv_transfer/kv_connector/v1/base.py
aphrodite/distributed/kv_transfer/kv_connector/v1/multi_connector.py
aphrodite/v1/core/block_pool.py
aphrodite/v1/core/sched/scheduler.py

feat: support KV events from connectors

---

aphrodite/config/__init__.py
aphrodite/endpoints/llm.py
aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/protocol.py
aphrodite/endpoints/openai/serving_engine.py
aphrodite/endpoints/openai/serving_pooling.py
aphrodite/engine/args_tools.py
aphrodite/engine/protocol.py
aphrodite/inputs/__init__.py
aphrodite/inputs/data.py
aphrodite/plugins/io_processors/__init__.py
aphrodite/plugins/io_processors/interface.py

feat: IO processor plugin for pooling models

---

aphrodite/endpoints/openai/protocol.py
aphrodite/endpoints/openai/speech_to_text.py
aphrodite/modeling/models/gemma3n_mm.py
aphrodite/modeling/models/interfaces.py
aphrodite/modeling/models/voxtral.py
aphrodite/modeling/models/whisper.py

For transcription and translation API endpoints.

feat: Gemma3n audio endpoint support

---

aphrodite/modeling/layers/rotary_embedding/mrope.py
aphrodite/modeling/models/keye.py
aphrodite/modeling/models/keye_vl1_5.py
aphrodite/modeling/models/registry.py

feat: support KeyeVL-1.5 model

---

aphrodite/modeling/model_loader/default_loader.py
aphrodite/modeling/model_loader/weight_utils.py

Add this to your launch params: `--model-loader-extra-config '{"enable_multithread_load": true, "num_threads": 8}'`. Tune the number of threads as needed.

feat: multi-threaded model weights loader

---

aphrodite/endpoints/openai/api_server.py
aphrodite/endpoints/openai/serving_kobold.py

Much cleaner this way, also fixes the broken Kobold API.

[API] chore: separate Kobold API code to its own serving class
